### ISSUE TITLE
Way to make read_array! call read_scalar for robustness

### ISSUE THREAD

**Issue by djsegal** [JuliaIO/JLD2.jl#114]
Related to:

+ https://discourse.julialang.org/t/way-to-migrate-jld2-data-to-have-new-fields-without-corruption/15309
+ https://discourse.julialang.org/t/what-is-the-idiomatic-way-to-undo-a-gensym/15354

JLD2 will break on restructuring an array but not a scalar.

Why does `read_array!` not call `read_scalar` over its elements?

**Comment by djsegal** [comment]
@simonster is there a reason this is not done?

**Comment by JonasIsensee** [comment]
Do you remember what this was about?
E.g. is there an up to date examples of what doesn't work and what could work with such a change?
