### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaIO/JLD2.jl#119]
How do you propose this could be debugged?

signal (11): Segmentation fault
in expression starting at /mnt/c/Users/PetrKrysl/Documents/Work-in-progress/H2Libjl/investigations/sphere/alusph_scat_1_dense.jl:138
_write at ./pointer.jl:155 [inlined]
write at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/misc.jl:27 [inlined]
commit at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/datatypes.jl:259
macro expansion at ./printf.jl:159 [inlined]
h5fieldtype at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/data.jl:838
unknown function (ip: 0x7fdcf32039b7)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
h5type at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/data.jl:846 [inlined]
commit at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/data.jl:223
unknown function (ip: 0x7fdcf32009c7)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
commit_compound at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/data.jl:211
unknown function (ip: 0x7fdd0aaccaa7)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
h5type at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/data.jl:163
unknown function (ip: 0x7fdd0aacb9e3)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
h5type at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/data.jl:168 [inlined]
write_dataset at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/datasets.jl:521 [inlined]
write at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/groups.jl:119
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
write at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/JLD2.jl:327
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
#1 at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/loadsave.jl:50
#jldopen#31 at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/loadsave.jl:4
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
jldopen at /home/pkrysl/.julia/packages/JLD2/KjBIK/src/loadsave.jl:2
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:324
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:428
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:363 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7fdd11a4e4ef)
unknown function (ip: 0x6)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:787
jl_eval_module_expr at /buildworker/worker/package_linux64/build/src/toplevel.c:233
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:616
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:838
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:821
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
include at ./client.jl:388
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:324
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:428
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:363 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7fdd0fb9c0af)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:787
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/builtins.c:622
eval at ./boot.jl:319
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:85
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:117 [inlined]
#28 at ./task.jl:259
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1536 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:268
unknown function (ip: 0xffffffffffffffff)
Allocations: 182566007 (Pool: 182500032; Big: 65975); GC: 647
Segmentation fault (core dumped)

**Comment by JonasIsensee** [comment]
Hi,
can you still reproduce this issue?

**Comment by PetrKryslUCSD** [comment]
Sorry, no.
