### ISSUE TITLE
filename argument must be a string literal unless variable names are specified

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaIO/JLD2.jl#121]
I have a JLD2 file `cpd_results/align_B13_to_B1.jld2`.

This works like a charm:
```
@load "cpd_results/align_B13_to_B1.jld2"
```

On the other hand,
```
cage_x = "B13"
cage_y = "B1"
@load @sprintf("cpd_results/align_%s_to_%s.jld2", cage_x, cage_y)
```
yields an error:

```
ERROR: LoadError: ArgumentError: filename argument must be a string literal unless variable names are specified
Stacktrace:
 [1] @load(::LineNumberNode, ::Module, ::Any, ::Vararg{Any,N} where N) at /nfs/stak/users/simoncor/.julia/packages/JLD2/KjBIK/src/loadsave.jl:59
in expression starting at REPL[25]:1
```

Why is this, and how else can I automatically load many files with different filenames in a loop?

**Comment by SimonEnsemble** [comment]
```
read(jldopen(@sprintf("cpd_results/align_%s_to_%s.jld2", cage_x, cage_y)), "ℓ")
```
gives me a particular variable "ℓ", but it would be much easier to load in all vars. at once as `@load` does, or for `@load` to work with string formatting.

**Comment by JonasIsensee** [comment]
I would suggest using the FileIO interface.

As far as I understand, the `@load` macro requires this because of a macro scoping problem.
