### ISSUE TITLE
"saved type ... is missing field ... in workspace type"

### ISSUE THREAD

**Issue by marius311** [JuliaIO/JLD2.jl#130]
I'm getting the following error trying to load a JLD2 file on one system, which was saved on another system. 

```
┌ Warning: saved type getfield(CMBLensing, Symbol("##303#309")){Loess.LoessModel{Float64},Float64} is missing field lnP in workspace type; reconstructing
└ @ JLD2 /home/marius/.julia/packages/JLD2/KjBIK/src/data.jl:402
```

On the system on which it was created, the file loads without warning. Both systems have the same version of Julia (1.1.0), JLD2 (0.1.2), Loess (0.5.0), and this "CMBLensing" package mentioned above. I've done `using CMBLensing` and `using Loess` before loading the file on both systems. 

The object which is being reconstructed is an anonymous function, the code which constructs it looks like this, its the `iP` object

```julia
ilnP = loess(xs,lnPs)
(iP, Px) = let A = quadgk(x->exp(Loess.predict(ilnP,x)),xmin,xmax)[1]
    (x->exp(Loess.predict(ilnP,x))/A,
     @. exp(lnPs)/A)
end
```

Note that there is nothing called `lnP` (as mentioned in the warning), although there is an `ilnP`. Elsewhere in the JLD2 file there is a dictionary with a key `:lnP`, which is reconstructed fine. I'm not sure what the `lnP` in the warning is refering to or if that's a hint. 

Any ideas what's going on or how I can debug this? Thanks.

**Comment by JonasIsensee** [comment]
Alright, since this is a well-known problem I have opened
https://github.com/JuliaIO/JLD2.jl/issues/208
as a feature request to allow serialization of functions and closures.

I'm closing this to cleanup the backlog of issues.
