### ISSUE TITLE
Corruption when saving  Vector{Union{Missing,T}}   

### ISSUE THREAD

**Issue by dylanfesta** [JuliaIO/JLD2.jl#131]
It seems that JLD2 switches values to `missing` randomly when I try to save a vector that contains missings.  

Minimal example:
```julia
using JLD2 
aaa =Vector{Union{Bool,Missing}}(undef,10_000)
aaa .= true
cd(@__DIR__())
jldopen("test1.jld2","w") do f
  f["aaa"] = aaa
end
aaa_read = jldopen("test1.jld2","r") do f
  f["aaa"]
end
@show any(ismissing.(aaa)) # false
@show any(ismissing.(aaa_read)) # true
@show count(ismissing.(aaa_read)) #  changes at each run 486, 764, etc 
```
(the bug appears also if I use `Int32` , I did not try other types, but I assume it is always present)

This might be a duplicate of issue #111 , except it is much more general than DataFrames.  Maybe it is not fixed, people should at least see a warning when saving anything that contains missings?

**Comment by smury** [comment]
I have the same issue with arrays of Union{Int64,Missing}, though I have so far only noticed that 0 is replaced by missing.
`
using JLD2 
x=T[]
append!(x,0)
@save "test.jld2" x
@load "test.jld2" x #x now contains missing rather than 0
`

**Comment by JonasIsensee** [comment]
Hi @dylanfesta ,

on Julia v1.4 and JLD2 v0.1.13 I can not reproduce this error.
Nor the one in #111 

I can't quite pinpoint what brought the change though.
Do you remember what julia version you were using ?

**Comment by dylanfesta** [comment]
Yes, I tried again the code on the most recent version of Julia, and the bug seems gone.
I think at the time I was simply using the most recent version of Julia and of JLD2 I had.

Should I close the issue? Or perhaps it should be tested on the Julia LTS version, too? And on other platforms (mine is Linux)? Is there a way to test it on Travis, or something along those lines? (I am still a novice, but I like all those tools)

**Comment by JonasIsensee** [comment]
If you would like to help out, you could make a small PR that adds a test for this.
(You can probably add a block to `test/loadsave.jl` and maybe write something like `# issue #131` above your code)

Then this will be tested on travis on different OS in the future.

**Comment by dylanfesta** [comment]
@JonasIsensee  Done! Should I close the issue?
