### ISSUE TITLE
Global `compress` option

### ISSUE THREAD

**Issue by alyst** [JuliaIO/JLD2.jl#133]
At the moment compression is disabled by default, and since it's not possible to pass options to `@save` macro, all the JLD2 files created with `@save` are uncompressed (unnecessarily huge).

It would be nice to add some mechanism to set the global `compress` option that would be used as the default choice for `compress=` arg in `jldopen()`. E.g. `JLD2.set_compress(true/false)` (+ `JLD2.compress()` getter).

The alternative would be to support `compress=` option in `@save` macro, but that would interfere with the potential `var=expr` feature (#132).

**Comment by JonasIsensee** [comment]
Hi @alyst !
Have a look at #198
This implements a better save macro that allows passing options to the function as well as assignment syntax.
What do you think?
