### ISSUE TITLE
Loading file without known type throws recussive warnings, interrupt resistant

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaIO/JLD2.jl#137]
If I try to load data saved from a custom Julia type without the type defined, I get repetitive warnings each time an array of that type is attempted to be loaded. I'd rather just interrupt (Ctrl+C) and regain control to load the type definition. However, the interrupt gets ignored and it keeps going.

I'd like to see either: 1) interrupt stops whole loading method, not just part of the load operation; and/or 2) missing type definition is considered an error unless suppressed by an argument.

**Comment by JonasIsensee** [comment]
this should be greatly improved by #476
