### ISSUE TITLE
Types in nested modules are not resolved properly

### ISSUE THREAD

**Issue by staticfloat** [JuliaIO/JLD2.jl#154]
Perhaps this isn't supposed to work, but I'm surprised by it; it seems that if I have a type that is available as `A.B.C`, this is not resolvable, whereas something that is simply `A.C` is.  Example using stdlibs:

```julia
using JLD2

# Always start fresh
rm("test.jld"; force=true)

# Write out jld file in child module
module Child
using JLD2, LinearAlgebra, Pkg
jldopen("test.jld", "w") do io
    # Symmetric is correctly loadable
    io["linalg_obj"] = Symmetric(randn(2,2,))

    # PackgeSpec is not loadable, because it's actually Pkg.Types.PackageSpec; it will be "reconstructed"
    io["pkg_types_obj"] = PackageSpec(;name = "Foo")
end
@info("Wrote out to test.jld")

# Parent module will call do_read()
function do_read()
    jldopen("test.jld", "r") do io
        io["linalg_obj"], io["pkg_types_obj"]
    end
end
end # module Child

# Read it out in parent module (where Pkg and LinearAlgebra don't exist)
import .Child
@show Child.do_read()
```

I have tried @DilumAluthge's fixes in #151 and they do not seem to help.

**Comment by DilumAluthge** [comment]
Inside what module scope are you doing the load?

**Comment by staticfloat** [comment]
In the example above, `do_read()` is defined within the child module, and is invoked from `Main`.

**Comment by janEbert** [comment]
I encountered this same problem in both master and #153.
#126 fixed it, though, with an `import` of the nested module in global scope.

**Comment by DilumAluthge** [comment]
@staticfloat I just tried your MWE with #126, and those changes fixed it for me.

**Comment by staticfloat** [comment]
Confirmed fixed!
