### ISSUE TITLE
prevent overwriting using @save

### ISSUE THREAD

**Issue by JianghuiDu** [JuliaIO/JLD2.jl#172]
I have made the mistake of using @save multiple times and it's quite exacerbating.
Say I already have a file `a.jld2` in my folder and sometimes I accidentally  `@save "a.jld2" x` when x doesn't yet exist. This reports error but still creates an empty file `a.jld2` that overwrites the original one which contain the right data. Is there a way to prevent overwriting existing files? I think itshould be the default option of such `save` or `write` functions.

**Comment by JonasIsensee** [comment]
I'm curious. For me this does not produce any error and simply overwrites the old file.
What versions are you using ?
Can you provide a minimal working/failing example?
