### ISSUE TITLE
Type Resolution with changing module paths

### ISSUE THREAD

**Issue by bjarthur** [JuliaIO/JLD2.jl#182]
riffing off of @ChrisRackauckas 's test case in https://github.com/JuliaIO/JLD2.jl/issues/122 , i get errors when trying to load a jld2 file that was saved in a submodule.  note that i have only add two lines to his code (`module SubModule` and `end #SubModule`).  would it be easy to get JLD2 to [work even harder](https://github.com/JuliaIO/JLD2.jl/pull/151) to find the types?

```
module SubModule

module TestModule
    struct MyHardStruct{T,T2,T3}
        f::T
        u::T2
        p::T3
    end
    function (m::MyHardStruct)(t)
        m.u[2]*t + (1-t)*m.u[1]
    end
    export MyHardStruct
end
using .TestModule
function f(u,p,t)
    [u[1],u[2]]
end
u = [[1.0,3.0],[5.0,5.0]]
p = (1.0,2.0,3.0)
m = MyHardStruct(f,u,p)

using JLD2
@save "out.jld2" m

end #SubModule

# New session

module TestModule
    struct MyHardStruct{T,T2,T3}
        f::T
        u::T2
        p::T3
    end
    function (m::MyHardStruct)(t)
        m.u[2]*t + (1-t)*m.u[1]
    end
    export MyHardStruct
end
using .TestModule, JLD2, Test
function f(u,p,t)
    [u[1],u[2]]
end
JLD2.@load "out.jld2" m
@test m(0.5) == [3.0,4.0]
```

**Comment by andreyzhitnikov** [comment]
I have similar problem.

**Comment by JonasIsensee** [comment]
There are multiple problems here:

For one: JLD2 currently does not support storing functions.
(it will try to store the struct but not the methods attached to it)

The second problem is: JLD2 has to figure out somehow what type to reconstruct.
From the error message you can see that in the file it reads
`Main.SubModule.TestModule.MyHardStruct`
which is not defined in the new session. There are some very simple heuristics of where JLD2 will attempt to search for the type definition but apparently it does not find it here.
(If your `Main` scope got sufficiently full, searching could take forever....)

I guess I'll remove the bug label and leave this issue as a reminder to maybe build a better type resolution at some point.
