### ISSUE TITLE
Under Julia 1.4 error reading files saved under Julia 1.3

### ISSUE THREAD

**Issue by Eben60** [JuliaIO/JLD2.jl#185]
[2020-04-02_16.12.48_cond_degree.zip](https://github.com/JuliaIO/JLD2.jl/files/4463343/2020-04-02_16.12.48_cond_degree.zip)

This file was saved under Julia 1.3 and contains several saved variables. One of them, the variable `moreargs` (see below) cannot now be read under 1.4 (the file readable OK under 1.3). Files saved under 1.4 can be read both with 1.3 and 1.4.

`moreargs = (pdict = Dict{String,Any}("t_ramp_type" => "exponential","membr_diam" => "(\"axis\", 2)","membr_perm" => "20","vol_cm3" => "453","temp_en" => "5","temp_st" => "80","rh_ramp_type" => "exponential","factor" => "0","env_rh_ramp_t_char" => "(\"axis\", 1, PyObject <function scaleLog2 at 0x000000003DD47EE8>, Any[])","heat_Tdiff" => "30","ranges" => "Tuple{Real,Float64}[(0.1, 2495.329850015803), (3, 30.0)]","rh_st" => "0.7","env_t_ramp_t_char" => "(\"axis\", 1, PyObject <function scaleLog2 at 0x000000003DD47EE8>, Any[])","encl_tau_therm" => "600","rh_en" => "0.2"), elapsed_time = 43.169658)`

**Comment by JonasIsensee** [comment]
Thank you for reporting this.

I'm afraid I won't have the time to fix transitions from previous julia versions but I hope that some compatibility mode will be possible in the future.

Any suggestions towards a solution would be very welcome.
For data that you want to open in different julia versions it may be helpful to not serialize any advanced types such as these PyObjects. I assume that these may be the problem and the encoding changed between versions.

**Comment by Eben60** [comment]
Some problems with reading complex data structures in future Julia versions could be unavoidable. Avoiding saving such data in the first place is a reasonable advice.

Still, for the case that something went wrong, it would be nice to have some kind of "recovery mode", enabling to restore at least part of the data, with unreadable data replace by "missing" or some custom data type. I am not sure whether it is possible with the current verion of JLD2.
