### ISSUE TITLE
API: jldsave & save_object

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaIO/JLD2.jl#210]
The current JLD2 interface requires providing a name for each object that you save, so if I want to save a single object and then reload it later, I have to do something like this:

```julia
save("df.jld2", "df", df)
newdf = load("df.jld2", "df")
```

There are two main problems with this:

- It's more complicated than necessary for saving and loading a single object.
- THIS IS IMPORTANT: Loading an object requires that you remember the name under which you saved the object. This is very bad in my opinion.

Here's the much simpler interface that R uses for saving and loading a single object:

```r
saveRDS("saved_df.rds", df)
newdf <- readRDS("saved_df.rds")
```

It would be nice if JLD2 supported the same interface. I'm not sure whether it would be better to overload `save` and `load` for this, or to add new functions like `save_object` and `load_object`.

Sample syntax:

```julia
save_object("saved_df.jld2", df)
newdf = load_object("saved_df.jld2")
```

**Comment by JonasIsensee** [comment]
Hi @CameronBieganek ,

this is an interesting problem. I've had the same issue with HDF5-type files before.

> THIS IS IMPORTANT: Loading an object requires that you remember the name under which you saved the object. This is very bad in my opinion.
Note that the `FileIO` interface will `load("test.jld2")` all elements into a dictionary making the object names at least discoverable.
And this should also work.
```
julia> file = jldopen("example.jld2", "r")
JLDFile /Users/simon/example.jld2 (read-only)
 └─📂 mygroup
    └─🔢 mystuff
```

Of course what you suggest would be even more convenient. In principle your _sample syntax_ should be possible. (I would not like to burden the `save` & `load` syntax with yet another feature.)
The underlying HDF5 format that JLD2 implements has to have a name for any dataset !
So one way would be to define e.g.
```
save_object(filename, x) = save(filename, "single_stored_object", x)

load_object(filename) = load(filename, "single_stored_object")
```
but this is somewhat brittle. What should happen if the file wasn't written with that command?
To me it seems reasonable that this should work: 
```
save("test.jld2" , "data", data)
load_object("test.jld2")
```
Another question is how should `load_object` behave when 
more than one dataset is stored in the file?

**Comment by CameronBieganek** [comment]
Maybe to make things slightly less brittle, `save_object` can save files with a different extension. E.g., perhaps `save_object("testfile", x)` would write the file `"testfile.jld2o"`. And then `load_object` could throw an error if it is used on a file that does not have the `.jld2o` extension.

> Note that the FileIO interface will load("test.jld2") all elements into a dictionary making the object names at least discoverable.

The thing I don't like about this is that I have to interactively test my code in order to know the right way to call a function. Normally, one should be able to write code based on a documented API. But in this case the API is only discoverable via interacting with the file in the REPL.

**Comment by JonasIsensee** [comment]
Hi,
file extensions are really just conventions and have no real meaning,
so it could be a good idea to do what you suggest but it doesn't really solve the problem.

Here's a workaround for you though:
```
julia> d = Dict("a" => 1)
Dict{String,Int64} with 1 entry:
  "a" => 1

julia> only(d)
"a" => 1

julia> only(d).value
ERROR: type Pair has no field value
Stacktrace:
 [1] getproperty(::Pair{String,Int64}, ::Symbol) at ./Base.jl:33
 [2] top-level scope at REPL[4]:1

julia> only(d)[2]
1
```

So I guess you could simply define:
`save_object(fn, obj) = save(fn, "some_name", obj)`
`load_object(fn) = only(load(fn))[2]`
and then work with that

**Comment by CameronBieganek** [comment]
> file extensions are really just conventions and have no real meaning

Yeah, that's why I said "slightly less brittle". 😃 

---

> `load_object(fn) = last(only(load(fn)))`

That looks pretty good to me! It has the desired API and it throws an error if the file contains more than one object. And the error message is actually not too bad:

```julia
julia> only(Dict(:a=>1, :b=>2))
ERROR: ArgumentError: Collection has multiple elements, must contain exactly 1 element
Stacktrace:
 [1] only(::Dict{Symbol,Int64}) at ./iterators.jl:1287
 [2] top-level scope at REPL[2]:1
```

Although we could make the error message even better with something like this:

```julia
function load_object(fn)
    data = load(fn)
    if length(data) > 1
        throw(ArgumentError("File $fn contains more than one object. Use `load` or `@load` instead"))
    end
    last(data)
end
```

**Comment by JonasIsensee** [comment]
Yes, that is even better!

I would prefer not to use the FileIO interface though and use 
https://github.com/JuliaIO/JLD2.jl/blob/ddf8aa9b0a4a0fa535cad8b57471c1e43c645991/src/loadsave.jl#L147
directly. (In the future I plan to remove FileIO as a dependency and use Requires for the API instead.)

If you would like, you could make a PR for this.
The code should go at the end of `loadsave.jl`, tests in the file of the same name and a small section in the Readme would be good.

**Comment by UtkarshChemE** [comment]
This one should be closed
