### ISSUE TITLE
Magic bytes

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaIO/JLD2.jl#211]
Hi,
the changes that I want to make in #206 modify the format in that older JLD2 versions cannot read some newer files.
(Old files can still be read)
Beside bumping the version number of the package, I feel we should also increase the version number 
of the file format in the magic byte file header. (e.g. move from v0.2 to v0.3)

However I just noticed that `JLD` and `JLD2` share essentially the same magic bytes:
```
# data formats
add_format(format"JLD", (unsafe_wrap(Vector{UInt8}, "Julia data file (HDF5), version 0.0"),
                         unsafe_wrap(Vector{UInt8}, "Julia data file (HDF5), version 0.1")), ".jld", [:JLD])
add_format(format"JLD2", "Julia data file (HDF5), version 0.2", ".jld2", [:JLD2])
```
and only differ by a version number.

This probably made sense a few years ago when JLD2 was still meant as a replacement for JLD but that is not very likely as of today.
What do you think? (Will JLD ever need higher version numbers?)
Should I still just add v0.3 for the magic bytes?
Should JLD2 change the header bytes completely to make it more distinct from JLD?

**Comment by JonasIsensee** [comment]
@timholy 
What is your opinion on this?

**Comment by timholy** [comment]
Interesting question. If this package is unlikely to replace JLD, then yes, it seems reasonable that they should have a more significant difference in their magic bytes.

**Comment by JonasIsensee** [comment]
Thank you!

I will introduce new magic bytes soon.
Suggestions anyone?
