### ISSUE TITLE
Handling of files with groups

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaIO/JLD2.jl#224]
The standard API, `@load` does not handle
files with groups in them. (Either skips them or errors)

Instead we could load groups as `Dict{String, Any}` in the future.

Additionally one could consider modifying the functionality of `@save` and `FileIO.save`
to automatically convert nested `Dict{String, Any}` into groups.

Any thoughts?

**Comment by jebej** [comment]
Hello, does the ability to save nested dicts as groups exist now?

**Comment by JonasIsensee** [comment]
You can now load nested groups into nested dicts.
Saving nested dicts as groups has not been added.
