### ISSUE TITLE
Improve compression

### ISSUE THREAD

**Issue by simonster** [JuliaIO/JLD2.jl#23]
Right now compression is implemented in the most naive possible way, and only zlib is implemented. It would be nice to have a faster option (e.g. Blosc or LZ4) and also not have to buffer everything in memory before writing to disk.

**Comment by JonasIsensee** [comment]
With `TranscodingStreams.jl`, `Blosc.jl` and `CodecLz4.jl` this should be possible. They all support streaming compression which would allow
 - not having to buffer everything in memory
 - allow compression on arrays where the memory layout is different from the disk layout. (this should already be possible but is not allowed)

One thing that needs to be discussed is the API to specify compression levels, and the Compression library.

The filter ids for compatibility are listed here : https://portal.hdfgroup.org/display/support/Registered+Filter+Plugins
(blosc: 32001, LZ4: 32004)

**Comment by JonasIsensee** [comment]
Implemented in #264
