### ISSUE TITLE
is keys(fh) documented

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaIO/JLD2.jl#236]
I am not sure that this is documented
```
fh = jldopen(FileName,"r")
  println(keys(fh))
close(fh)
``` 
If it actually is, where do I find it? If not, is a PR of the readme welcomed?

**Comment by JonasIsensee** [comment]
Hi @PaulSoderlind !
you're right, this isn't actually documented but it should be.
I'd say that in general `Group` and `JLDFile` try to imitate a `Dict` so it makes sense for `Base.keys` to be overloaded with the canonical behaviour..
(Only that entries can't be deleted or changed)

A PR that explains this a bit and lists available API functions would be very welcome!
(`keys`, `haskey`, `get`)
Also if there are more API functions that you feel are missing just open an issue or make a PR for it yourself.
