### ISSUE TITLE
Recover (some) data from lost data structure

### ISSUE THREAD

**Issue by rveltz** [JuliaIO/JLD2.jl#242]
Hi,

I have saved data 2 years ago but I lost the data structure (basically the fields of my struct have changed). Can I recover some information ?

Thank you,

Best

**Comment by JonasIsensee** [comment]
Hi @rveltz !
Recovery should be possible.

What happens when you just try to load the file ?
Ideally JLD2 should figure out that the new type is changed and then instead reconstruct a `ReconstructedType`
that one then has all the fields of the old one and you can access them.

**Comment by rveltz** [comment]
Yes, but with the new type, some fields are discarded... Can I get them anyway?

```
julia> FileIO.load("fbp1-stripes-detect3-droite-finalise.jld2")
┌ Warning: the following fields are present in type ContResult{NamedTuple{(:x1, :x2, :x3, :x4, :x5, :x6, :x7, :x8, :param, :itnewton, :ds, :theta, :step),Tuple{Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Int64,Float64,Float64,Int64}},Array{Complex{Float64},1},Nothing,GenericBifPoint{Float64,NamedTuple{(:x1, :x2, :x3, :x4, :x5, :x6, :x7, :x8),NTuple{8,Float64}},Array{Float64,3}},GenericBifPoint{Float64,NamedTuple{(:x1, :x2, :x3, :x4, :x5, :x6, :x7, :x8),NTuple{8,Float64}},Array{Float64,3}},Array{NamedTuple{(:x, :p, :step),Tuple{Array{Float64,3},Float64,Int64}},1},Nothing,NamedTuple{(:mu, :theta, :scalingIext, :Rint, :Cint, :ratio_space, :spatialExtention, :rotationinv, :α, :scale_factor),Tuple{Float64,Float64,Float64,Float64,Float64,Float64,Float64,Bool,Float64,Float64}},Setfield.PropertyLens{:mu}} saved in the file but not present in the type the workspace:
│
│ stability
│ n_imag
│ n_unstable,
│
│ Data in these fields will not be accessible
└ @ JLD2 ~/.julia/packages/JLD2/eU405/src/data.jl:438
```

**Comment by rveltz** [comment]
Or can I see to `load`, discard the structure `ContResult`?

**Comment by JonasIsensee** [comment]
Hm, I must admit that I don't fully understand.

> Or can I see to `load`, discard the structure `ContResult`?

The `load` supports loading only specific fields as `load(filename, "fieldname")`.
What you can't do is to tell `load` to *forget* about type definitions.

Here are some general ideas:
Suppose you have a type `B` that used to have 3 fields:
```julia
julia> struct B{T,S} x::T; y::S;z::S; end

julia> @save "test.jld2" b=B("x", 21, 42)
```
But now it has been changed to have only fields `x` and `y`.

In a new julia session you get:

```julia
julia> struct B{T, S} x::T; y::S; end

julia> @load "test.jld2"
┌ Warning: the following fields are present in type B{String,Int64} saved in the file but not present in the type the workspace:
│ 
│ z,
│ 
│ Data in these fields will not be accessible
└ @ JLD2 ~/.julia/dev/JLD2/src/data.jl:438
1-element Array{Symbol,1}:
 :b

julia> b
B{String,Int64}("x", 21)
```
and field `z` is not accessible.

If you want to get all fields you can *just not define that type*:
```
julia> using JLD2

julia> @load "test.jld2"
┌ Warning: type Main.B{String,Int64} does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/dev/JLD2/src/data.jl:1248
1-element Array{Symbol,1}:
 :b

julia> b
JLD2.ReconstructedTypes.var"##Main.B{String,Int64}#253"("x", 21, 42)
```

but then if the type was saved as part of a larger file and all definitions are in the same module then you're in trouble again because ALL definitions are now gone.

A last option is to selectively hide structs from `load` by doing

```julia
julia> module A
       struct B{T,S} x::T; y::S; z::S; end
       end
Main.A

julia> using JLD2

julia> @load "test.jld2"
┌ Warning: type Main.B{String,Int64} does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/dev/JLD2/src/data.jl:1248
1-element Array{Symbol,1}:
 :b

julia> using Main.A:B

julia> @load "test.jld2"
1-element Array{Symbol,1}:
 :b

julia> b
B{String,Int64}("x", 21, 42)
```


So in principle you might be able to load everything from your file by doing

```julia
module OldStruct
    struct OldStructDef
        fields....
    end
end
using Main.OldStruct: OldStructDef

module OtherImport
    using OtherDefsModule
end

using Main.OtherImport: My, Other, Type, Defs

using JLD2, FileIO
data = load("oldfile.jld2")
# and then convert between OldStructDef and OtherImport.OtherDefsModule.NewStructDef
```

**Comment by rveltz** [comment]
> What you can't do is to tell load to forget about type definitions.

I think you said it. I was thinking of a way to force JLD2 to use its `ReconstructedTypes` regardless of what are the types in `scope`. Something like `load(file, :useReconstructedTypesOnly)`. But your module trick seems the way to go.

Thank you a lot for your detailed description.

**Comment by JonasIsensee** [comment]
A feature that does what you suggest sounds interesting
but I also don't see a strong need for it at this point.

PRs are always welcome ;) 

I guess I'll tag this as solved for now and add a documentation tag
to include the above in module trick in a future improved documentation.

**Comment by JonasIsensee** [comment]
v0.4.21 allows for explicit type remapping. 
That will most likely be the simplest solution going forward.
