### ISSUE TITLE
Piracy inside JLD2

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaIO/JLD2.jl#253]
I found this piece of type piracy while playing around with `SnoopCompile` and looking for invalidations.

https://github.com/JuliaIO/JLD2.jl/blob/f6ea9111f1e50ff007f7916f4de7a76f793d3d59/src/misc.jl#L6-L38

I'm not comfortable with this being a normal part of the procedure.
```julia
julia> struct A; x::Int; y::Int8; end

julia> sizeof(A)
16

julia> using JLD2

julia> JLD2.define_packed(A)

julia> sizeof(A)
9

```

**Comment by JonasIsensee** [comment]
To get rid of this piracy we need to introduce new names to replace

`Base.write`
`Base.read`
`Base.unsafe_load`
`Base.unsafe_store!`
`Base.sizeof`

**Comment by timholy** [comment]
Two immediate thoughts:
- `jld_write`, `jld_read`, etc
- call them `write`, `read`, etc, without extending the Base methods. Then when you need to call the Base versions, use module scoping `Base.write`.

I somewhat lean towards the second, *but* it is worth acknowledging the potential confusion it could cause for people reading the code and just assuming that these refer to the Base methods.

**Comment by JonasIsensee** [comment]
> without extending the Base methods

I hadn't even thought of that.

Having had to read a lot of source code of JLD2 in the last few months I'm leaning towards the first option.
It is hard to figure out in which cases the "normal" julia methods are called and when there are custom overloads instead.

Currently there is already `jldopen`, `JLDFile`, but also `jlconvert`.
It'd be nice to be able to reuse one of those two styles instead of introducing another one.
`jldwrite` & `jldread` or `jlwrite` & `jlread`
