### ISSUE TITLE
Super slow read times off network filesystem? 

### ISSUE THREAD

**Issue by marius311** [JuliaIO/JLD2.jl#262]
I have a 2GB JLD2 file which I am reading via `jldopen` and reading only specific keys within the file (I read about 20 keys out of 30). On my laptop the read takes about 20 seconds. However, when the file is on a network filesystem on a cluster and I read it from that cluster, it takes about 100 seconds, sometimes seeming to hang for a really long time on reading specific keys, with others going about as fast as normal. 

I don't think the overhead is network transfer, e.g. `cat the_file.jld2 > /dev/null` is <1 second. I've tried both `jldopen("the_file.jld2", false, false, false, MmapIO)` and `jldopen("the_file.jld2", false, false, false, IOStream)` and both are just as slow. 

Any suggestions how I can figure out whats slowing it down and improve it?

**Comment by JonasIsensee** [comment]
Hi @marius311,

that sounds indeed a bit odd and annoying. 


Does it still take as long when you load the file for the second time? (e.g. new scope or new julia session) 
As far as I know, NFS systems cache files on your local machine, so subsequent reads are usually much faster. 
(at least on the cluster I work on)
On the other hand, that cache has a finite size so maybe that is set up in an odd way? (<2GB though that would be very odd) 
Have a look at maybr `htop` to see if you julia process spends a lot of time in `D` state. (waiting for IO)

**Comment by marius311** [comment]
Thanks for the suggestions and quick reply. The second read is no faster. `htop` shows Julia at 100% the entire read and its on `R`, not `D`. I do notice the node is 162/188GB memory used and 7.75/8GB swap used. While I was reading it, mine was the only task really running, load is `0.59 0.59 0.43`. 

I did just try the read from one of the compute nodes rather than shared nodes on this cluster and there there's no slow down, the read takes about 10 seconds. 

Not sure what to make of it, could well be an issue with configuration on this cluster. But if you have idea if there might be interplay with what JLD2 is doing under the hood, much appreciated.

**Comment by JonasIsensee** [comment]
Uh, the swap is a likely candidate. 
Whenever swapping is involved runtimes diverge...

I'd start with trying to free up some memory.

**Comment by JonasIsensee** [comment]
But even without this problem, 20s load time seems rather excessive. Can you share some details about the file structure? What version of JLD2 are you on?

**Comment by marius311** [comment]
Is there any reason swap would be involved here given theres ~26GB of free memory? Fwiw the compute nodes which load this fast seem to be at 6.97G/6.97G swap space before I do anything on them (with about 40GB RAM free), and it doesn't seem to be an issue. 

Most of the size of the file comes from about 10k 256×256 Float32 arrays, so the 20s doesn't seem unreasonable to me, given they're not stored in a single contiguous array, but there's also various NamedTuples, Dicts, and other structures in there.

**Comment by JonasIsensee** [comment]
hm, I guess you could have a look at what the profiler says? (e.g. also to find differences between the different machines?)
Another thing would be to check memory allocations.

**Comment by JonasIsensee** [comment]
@marius311 
I'd be interested in the results of the profiling.
Do these files contain sensitive information? Would you be willing to publicly or privately share one (or parts) of those?
JLD2 is lacking proper real-life benchmarks and thus I don't really know whether my development introduces performance regressions.

**Comment by marius311** [comment]
Sorry would have replied earlier, not that it would have been an issue, but technically we just published the paper that makes this file OK to share last week :)

Try:

```sh

# 3.7GB download
shell> wget https://portal.nersc.gov/project/cmbs4/marius/test_chain.jld2

pkg> add CMBLensing@0.4.0

julia> using CMBLensing

julia> load_chains("test_chain.jld2")
```

The relevant code in that function is [this](https://github.com/marius311/CMBLensing.jl/blob/v0.4.0/src/chains.jl#L46-L61). It basically just reads the keys "chunk_1", "chunk_2", etc... out of that file one by one. Its ~20 seconds to read on a good day, and 2-3 min on a bad day off a network filesystem. 

Happy if this is a useful benchmark, but otherwise no worries if you never look at it. I still haven't had a chance to profile, but will report back if I find anything useful.

**Comment by JonasIsensee** [comment]
Hi @marius311 !

I finally managed to have a quick look at your code.
If I understand this correctly:
https://github.com/marius311/CMBLensing.jl/blob/32e81591e69f204f77c3f3cf688520464c37670c/src/sampling.jl#L389
then you append to your files many many times.

It's great that JLD2 allows this, but it also becomes highly inefficient due
to the design of the HDF5 standard.
Essentially JLD2/HDF5 writes a table of contents at the end of your file.
whenever you add new datasets it will add to the table of contents
by adding a "continued list" again at the end of the file.
(In order to not have to move already written data)

When you do this very often (and in particular close your file in between)
then you will spread out your toc throughout the whole document.
This is bad on any file system but NFS suffers particularly.

**Comment by JonasIsensee** [comment]
Hi @marius311 ,

I found out that for some of my IO heavy analysis I can speed things up considerably by
doing something like
```
tmpfile = mktempdir(;cleanup=false)#*"/temp.jld2"
cp(myfile, tmpfile)
jldopen(tmpfile, "r") do 
...
end
rm(tmpfile)
```
