### ISSUE TITLE
save type NTuple is missing field...

### ISSUE THREAD

**Issue by mkarikom** [JuliaIO/JLD2.jl#263]
I can't seem to replicate this, but somehow I end up loading a tuple that no longer supports iteration.
Here is the error:
```
┌ Warning: saved type NTuple{926,Dict{Symbol,Any}} is missing field 159 in workspace type; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/eU405/src/data.jl:404
```
Can I somehow cast this back to what it should be

**Comment by JonasIsensee** [comment]
Uh, now that is funky, that shouldn't happen.

Please excuse my curiosity, but what were you doing with a >900 element tuple? 
Can you tell me:
What julia version are you using?
What JLD2 version? (loading and what was used to write the file?)

**Comment by mkarikom** [comment]
Hi, sure here are some details

1. tuple simplest way to implement metagraphs.jl vertex properties as sets (I get helpful errors if non-uniqueness happens etc) with nested elements 
2.  julia 1.5.2
3.  [033835bb] JLD2 v0.2.4

**Comment by JonasIsensee** [comment]
hm, 
I'm not sure what happened there. 
Generally, I'd say that very long tuples are not great for either the compiler or JLD2.
(Inside JLD2 the tuple is converted into a struct with as many fields, so an array would be better for storing)
Of course, this should still work, though.

If you still have the offending file available, then you could share it with me and I'll have a closer look, if I can make sure this won't happen again.

**Comment by mkarikom** [comment]
ok that makes sense.  please see file below for reference.

you should see something weird if you do:
```
using MetaGraphs.jl
@load gcg.jld2
typeof(props(gcg,423)[:orthoDist][0][:members])
```
thanks!

[gcg.zip](https://github.com/JuliaIO/JLD2.jl/files/5648253/gcg.zip)

**Comment by JonasIsensee** [comment]
I can't quite figure out whats wrong with your file. `h5dump` lists element 159 just fine.

I made a small PR draft #265 that will convert tuples to vectors prior to writing.
Could you test out whether that solves the problem?

Also, as I mentioned I'm not fully convinced that long tuples are a great idea in the first place
so I'm not sure whether I'd actually want to merge my own PR.
You could help by getting people more educated on this topic than me to chime in.

**Comment by mkarikom** [comment]
Thanks for this,
Hm I'm sorry about that, it's possible I miswrote the index, I'll double
check.
Until I hear otherwise, I'm going to take your word that it's probably best
to just do an array.
I would still like to check out your update, though.
Do you see anything wrong with the following?:
```
(GCom) pkg> add JLD2#ntpules
    Cloning git-repo `https://github.com/JuliaIO/JLD2.jl.git`
<https://github.com/JuliaIO/JLD2.jl.git>
   Updating git-repo `https://github.com/JuliaIO/JLD2.jl.git`
<https://github.com/JuliaIO/JLD2.jl.git>
ERROR: Did not find rev ntpules in repository

(GCom) pkg>
```

**Comment by JonasIsensee** [comment]
Try `]add JLD2 #ntuples` with a space.

**Comment by mkarikom** [comment]
Sorry I meant to check this and got slammed with some other stuff.  
As things stood last week I had already done a kludge that just skipped over archives with tuple issues in order to meet a deadline (luckily this was insensitive to omission of particular .jld samples).
Next weekend I'll re-run everything and try to save it with the #ntuples fix and update you with results.  
thanks

**Comment by JonasIsensee** [comment]
Hi @mkarikom ,

do you want to dig into this further or should we close the issue?

**Comment by mkarikom** [comment]
Hi, @JonasIsensee.  Thanks for getting back to me on this and sorry about the late response.
Can we close this for now?  
I'm sorry, I'm not able to run the necessary tests on that particular project right now.
