### ISSUE TITLE
compress doesn't work when using a struct containing a union

### ISSUE THREAD

**Issue by ajaiantilal** [JuliaIO/JLD2.jl#266]
On v0.3.1:033835bb [Julia 1.5.3:788b2c77c1], after some back and forth on seeing why compression was not working with certain structs, I found that compression doesn't work when the sub-field is a union (but otherwise works like a charm on very nested structures - great job and much appreciated!). Below is my test code (Typ1 is the issue struct that doesn't get compressed)

```
using JLD2, FileIO
struct Typ1
    data2::Union{Int,Float32} #changing to other types like Nothing etc doesn't make a difference
end

struct Typ2
    data2::Int
end

sz = 10000;
a = Array{Typ1}(undef,sz,1);
for i=1:length(a)
    a[i] = Typ1(0);
end

b = Array{Typ2}(undef,sz,1);
for i=1:length(b)
    b[i] = Typ2(0);
end

c = Array{Union{Int,Float32}}(undef,sz,1);

@save "tmp.jld2" a {compress=true}
println("Typ1 (with union): with compression ", filesize("tmp.jld2"))
@save "tmp.jld2" a {compress=false}
println("Typ1 (with union): without compression ", filesize("tmp.jld2"))

@save "tmp.jld2" b {compress=true}
println("Typ2 (without union): with compression ", filesize("tmp.jld2"))
@save "tmp.jld2" b {compress=false}
println("Typ2 (without union): without compression ", filesize("tmp.jld2"))

@save "tmp.jld2" c {compress=true}
println("array of unions: with compression ", filesize("tmp.jld2"))
@save "tmp.jld2" c {compress=false}
println("array of unions: without compression ", filesize("tmp.jld2"))
```

output is
```
Typ1 (with union): with compression 1205333
Typ1 (with union): without compression 1205333
Typ2 (without union): with compression 5365
Typ2 (without union): without compression 85217
array of unions: with compression 5610
array of unions: without compression 135414
```

Thanks!

**Comment by JonasIsensee** [comment]
Hi @ajaiantilal,
Thank you for this detailed report!

I know that this is a bit frustrating but what you are describing is actually expected behaviour.

It is not possible to directly compress data sets with unions because `Union`s are different from other types.
In particular, they are not `isbits` and the memory layout depends on the value. (inside a union you find the selector determining which of the types is relevant and a pointer to the data).

Currently, the only option is to define a `custom serialization` procedure as explained at the bottom of the README
that converts your data to a different structure without any unions.

**Comment by ajaiantilal** [comment]
Hi @JonasIsensee 

thank you for the information and teaching me something about the way Unions are stored (i'm only like my first 20 hrs in Julia so this is my first instructive lesson about an issue). I initially thought it to be something related to the HDF5 layout [you know how small sizes might not get compressed at all].

oh no worries at all and I totally understand the amount of effort it will go into changing the code. After reading about how unions are stored i understand all the amount of effort and corner cases that need to be handled (i shudder to imagine structs within structs and with unions and other crazy layouts to handle and which may not be anyways efficiently stored by hdf5 because of all the metainfo that needs to be stored alongside actual data). Atleast this has given me ideas of refactoring my structs to not use unions as such because of how the storage is being done (inline vs pointers) and rather depend on more inline stuff.

feel free to close up this issue or keep it open (if you want others to find it in the future)

and thank you for your work. much appreciated.
