### ISSUE TITLE
Feature request: jldcache(func::Function, filename::String, path::String)

### ISSUE THREAD

**Issue by rssdev10** [JuliaIO/JLD2.jl#280]
```julia
using JLD2

function lldcache(func::Function, filename::String, path::String)
  local prepared = nothing
  if isfile(filename)
    jldopen(filename, "r") do file
      if haskey(file, path)
        prepared = file[path]
      end
    end
  end
  if isnothing(prepared)
    prepared = func(path)
    jldopen(filename, "a+") do file
      file[path] = prepared
    end
  end
  return prepared
end

for i = 1:3
  y = lldcache("tmp.jld", "data/y") do key
    rand(1:10, 5)
  end
  @show y
end
```

```
y = [9, 5, 7, 7, 6]
y = [9, 5, 7, 7, 6]
y = [9, 5, 7, 7, 6]
```

The feature might be useful when some precalculation for a big data set is required.

**Comment by JonasIsensee** [comment]
Hi @rssdev10,
this sounds indeed like a useful feature.

Have a look at `DrWatson.produce_or_load`
That function implements something very similar.

**Comment by rssdev10** [comment]
https://juliadynamics.github.io/DrWatson.jl/dev/save/#DrWatson.produce_or_load looks similar. But the name `produce_or_load` is not good. The real meaning is `load_or_produce_and_save`.... The approach which I shared, we are using in NLP project where we have some dictionaries in CSV. The processing time for them takes dozen minutes. For us, it is much more easy to don't think about a temporary storage, but have the primary files and run a program ones to calculate and store it. If something is changed in the CSV files, we have just to remove the temporary storage. Same for a docker image. We have to just run it once while building the image and forget about a load delay further. So, in that understanding this is a `cache` of the results.

Two concerns I have. Impossible to update something when we have multiple keys in the same file. And the solution is not type stable. 
The first concern in that use case is fixable by means of removing of the storage file. The second one is a common issue for JLD.

**Comment by rssdev10** [comment]
```julia
using JLD2

function lldcache(func::Function, filename::String, path::String, args...; kwargs...)
  local prepared = nothing
  if isfile(filename)
    jldopen(filename, "r") do file
      if haskey(file, path)
        prepared = file[path]
      end
    end
  end
  if isnothing(prepared)
    prepared = func(args...; kwargs...)
    jldopen(filename, "a+") do file
      file[path] = prepared
    end
  end
  return prepared
end

for i = 1:3
  y = lldcache("tmp.jld", "data/rand") do
    rand(1:10, 5)
  end
  @show y

  y = lldcache(range -> map(sin, range), "tmp.jld", "data/sin", 1:10)
  @show y

  y = lldcache(reduce, "tmp.jld", "data/reduce", +, 1:5; init=10)
  @show y
end
```

That might be more common solution. `lldcache` in that case takes the same arguments as a function surrounded by the cache.

**Comment by JonasIsensee** [comment]
As you state yourself, there is no general solution as to when a cache would need to updated.
Additionally, I feel that any such functionality would be more appropriate in something like
`DrWatson` as it is independent of the serialization backend (`JLD2`, `JLD`, `CSV`, `BSON`, `JSON`, ....)
and is more concerned about a general workflow.

**Comment by rssdev10** [comment]
I checked `produce_or_load` more carefully. It looks much more complicated in use than the single line wrapper over a function above. And, additionally, `produce_or_load` required to pack input and output attributes of the function into a dictionary. Definitely, we can say that it is not time critical when we need to save something, but it is an additional code which we have to write. Also, `produce_or_load` is doing something with git.

Regarding the mentioned serialization backend, it is not so important to have that selection. H5 compatible binary format looks enough. And it is convenient because I can put multiple records into the same file.

**Comment by rssdev10** [comment]
Code volume difference in the case of `produce_or_load` and a simple wrapper without additional options

```julia
using DrWatson

function g1(d)
    @unpack x, y = d

    result = x * y

    @dict result
end

x = 1
y = 2
res = produce_or_load(projectdir("tmp"), @dict(x, y), g1)
@unpack result = res[begin]
```

vs

```julia
g2(x, y) = x * y

result = jldcache(g2, "tmp.jld", "somekey", 1, 2)
```

Not sure that the second approach is apropriate to the DrWatson concepts of versioning in term of how to store it on a drive. And the second case, if it is a part of DrWatson, it will confuse new and current users of `produce_or_load`. I can say that even now the documentation for `produce_or_load` is not clear. `@dict/@unpack` is not a common way of programming in Julia.
Actually, there is no big difference for a final user of the function `jldcache` in which package it is located. But any way it would be good to write just minimal code around it.

**Comment by JonasIsensee** [comment]
Hi @rssdev10
