### ISSUE TITLE
Read a dictionary JLD2 file dumped by python in julia

### ISSUE THREAD

**Issue by smenaduce** [JuliaIO/JLD2.jl#292]
Hi,

I am trying to import a dictionary that I saved in python with the extension .jld2
First, I tried this code to do that:

```dict_name = load("path/dict_name.jld2")```

And, throw me this error:

```UndefVarError: load not defined```

Then, I tried with this:

```dict_name = @load "path/dict_name.jld2" ```

But it is imported as an array object.

**Could you help me with the correct code to import it as a dictionary?**

**Comment by JonasIsensee** [comment]
Hi!

To fix your first error you have to first do `using FileIO` because the `load` function name belongs to that package.

Second: how did you write a jld2 file with python?
I am not sure how that is possible

**Comment by JonasIsensee** [comment]
Hi @smenaduce !
Is this still relevant? If not, feel free to close this issue.
