### ISSUE TITLE
Feature request: allow begin-end blocks in @save for multiline arguments 

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaIO/JLD2.jl#295]
I prefer using JLD2's macro syntax over the FileIO interface with `save()` and `load()`, especially when reloading several variables to the same local variable names they were stored with. But unless I'm missing something obvious, JLD2's macros currently only accept arguments on one line:

```
@save "example.jld2" {compress=true} hello=variable1 world=variable2 foo=variable3 bar=variable4
@load "example.jld2" hello world foo bar
```

For readability it would be great if we could do something like this:

```
@save "example.jld2" begin
    hello=variable1
    world=variable2
    foo=variable3
    bar=variable4
    {compress=true} 
end
@load "example.jld2" hello world foo bar
```

**Comment by JonasIsensee** [comment]
Hi @niclasmattsson ,
this is an interesting idea.
However, I must admit that at first sight I'm not very convinced.
I'm also not a huge fan of these macros in their current form as
they add a lot of non-julian syntax.

DrWatson has a macro `@strdict` and
one can use it to do

```
data = @strdict hello=variable1 world=variable2 foo=variable3 bar=variable4
save("example.jld2", data; compress=true)
```
which I think is a much cleaner approach. 
Actually, no the assignment syntax is not yet possible. That will be added very soon.

You could chime in there to have multi line arguments added to that.
https://github.com/JuliaDynamics/DrWatson.jl/pull/240


Here's another way to do the same thing without any macros
but with julia's keyword argument syntax instead. 

```
julia> function strdict(;kwargs...)
       d = Dict{String, Any}()
       for (k,v) in kwargs
               d[string(k)] = v
       end
       return d
      end
strdict (generic function with 1 method)

julia> a= 1
1

julia> b= 2
2

julia> data = strdict(; a, c=b, d=1)
Dict{String, Any} with 3 entries:
  "c" => 2
  "a" => 1
  "d" => 1

julia> save("test.jld2", data)
```

**Comment by JonasIsensee** [comment]
I have implemented `jldsave` that will be available with the next releaset
