### ISSUE TITLE
@load macro cant receive filename string as variables

### ISSUE THREAD

**Issue by carlomontec** [JuliaIO/JLD2.jl#296]
I cant use @load using a filename as a variable:

```
julia> using JLD2

julia> hello = "world"
"world"

julia> foo = :bar
:bar

julia> @save "example.jld2" hello foo

julia> fn = "example.jld2"
"example.jld2"

julia> @load fn
ERROR: LoadError: MethodError: no method matching jldopen(::Symbol)
Closest candidates are:
  jldopen(::AbstractString) at /home/monjaraz/.julia/packages/JLD2/qncOK/src/JLD2.jl:307
  jldopen(::AbstractString, ::Bool, ::Bool, ::Bool) at /home/monjaraz/.julia/packages/JLD2/qncOK/src/JLD2.jl:218
  jldopen(::AbstractString, ::Bool, ::Bool, ::Bool, ::T; fallback, compress, mmaparrays) where T<:Union{Type{IOStream}, Type{JLD2.MmapIO}} at /home/monjaraz/.julia/packages/JLD2/qncOK/src/JLD2.jl:218
  ...
Stacktrace:
 [1] @load(::LineNumberNode, ::Module, ::Any, ::Vararg{Any,N} where N) at /home/monjaraz/.julia/packages/JLD2/qncOK/src/loadsave.jl:132
in expression starting at REPL[98]:1

julia> ^C

julia> string(fn)
"example.jld2"

julia> @load string(fn)
ERROR: LoadError: ArgumentError: filename argument must be a string literal unless variable names are specified
Stacktrace:
 [1] @load(::LineNumberNode, ::Module, ::Any, ::Vararg{Any,N} where N) at /home/monjaraz/.julia/packages/JLD2/qncOK/src/loadsave.jl:127
in expression starting at REPL[100]:1
```

**Comment by lhupe** [comment]
Using the load macro with variable file names is a bit tricky, see #51 for some background info.
Personally, I'd recommend avoiding the macros for non-interactive use — the jldopen API may be slightly less convenient, but it's much more transparent and gives you more control over what happens.

**Comment by JonasIsensee** [comment]
The `@load` and `@save` macros have non-obvious pitfalls.
I've never been a great fan but it seems that lots of people use it.
The explanation for your particular error is that
`@load` opens the file at compile time when the content of a variable is not yet known.

Maybe we could come up with a new and 
better syntax that avoids the weirdness of the macro and
still remains convenient.
Repurposing julia kwarg syntax might be an option
```
jld2save("test.jld2"; hello, foo)
```
which would do the same as
```
@save "test.jld2" hello foo

jldopen("test.jld2", "w") do f
    f["hello"] = hello
    f["foo"] = foo
end
```

**Comment by carlomontec** [comment]
Thank you all for your accurate and fast answer.  I was using the macro is to replicate the MATLAB behavior where the loaded variables are placed in the workspace directly, avoiding containing them in a dictionary.  I will stick to the  jldopen API.  The  julia kwarg syntax  idea sounds pretty nice. Best regards and thanks again, Carlo
