### ISSUE TITLE
Suppress warning "$TYPE does not exist in workspace; reconstructing" specifically

### ISSUE THREAD

**Issue by goretkin** [JuliaIO/JLD2.jl#315]
I'd be interested in still seeing all warnings, except I'd like to suppress warnings related to a reconstructing a type with a specific type string, or from a specific variable or field.

https://github.com/JuliaIO/JLD2.jl/blob/9a98c9ecf6eac3f5d8f2619e048f845816505e65/src/data/reconstructing_datatypes.jl#L358

**Comment by JonasIsensee** [comment]
Hi, 
this is an interesting request. 
Type reconstruction was always intended as a last resort and comes with performance penalties.
Can you elaborate on your use-case?

**Comment by goretkin** [comment]
I am stuffing some information into a JLD2 that I don't really need now, but might need later. The information comes from a package that the reader doesn't currently depend on. If I need to use the information later, the reader can load the appropriate package, and there would be no type reconstruction.

Come to think of it, I think a good solution is to separate out this extra information into its own "dataset"s and load only the relevant datasets with `load("example.jld2", "name1", "name2", ...)`

**Comment by JonasIsensee** [comment]
Yes, that seems like a much more sensible option!
