### ISSUE TITLE
World age issue related to recently introduced backwards compatible `ismutabletype`

### ISSUE THREAD

**Issue by mfherbst** [JuliaIO/JLD2.jl#325]
In our MPI-parallelised CI runs in DFTK (see e.g. https://github.com/JuliaMolSim/DFTK.jl/runs/2760704803#step:8:2107) we recently started encountering a world age issue, which was able to "quick-fix" by requiring JLD2 to be 0.4.7 or below, see also https://github.com/JuliaMolSim/DFTK.jl/issues/444.

Unfortunately the situation is a little involved, since we dynamically load JLD2 using `Requires` and moreover the issue only appears in our MPI-parallelised CI runs. In the CI runs not using MPI everything is fine, so this might well not be the "fault" of JLD2, but something more subtle on our end that just starts appearing now. Due to lack of time I did not yet manage to cook it down to a simple reproducer yet, unfortunately.

I just wanted to make you aware of this problem and ask for advice in case someone has any.

**Comment by JonasIsensee** [comment]
hm, this is annoying and very odd.
Sadly, I have no idea. 

Do the data structures differ with MPI ?

**Comment by mfherbst** [comment]
Yes in the sense that it has slightly different content. But unless I'm making a wrong assumption the types of the saved fields are the same (because I want MPI-written data to be readable from the serial code and vice versa). And for this sort of error it is the  types what should matter, no?

But I'll take another careful look at potentially differing types, that could definitely be something I might have missed. Thanks!

**Comment by JonasIsensee** [comment]
Yeah, that normally shouldn't make a difference.
The offending line is also odd.
These are jld2 internal signatures. I can't quite understand how the package could be *incompletely* loaded.
```
MethodError: no method matching ismutabletype(::Type{JLD2.RelOffset})
  The applicable method may be too new: running in world age 55215, while current world is 55936.
  Closest candidates are:
    ismutabletype(::Type) at /home/runner/.julia/packages/JLD2/vqQIU/src/backwards_compatibility.jl:32 (method too new to be called from this world context.)
```

**Comment by mfherbst** [comment]
Honestly not sure why, but this problem magically disappeared recently. I'm closing this. Let's hope it does not appear again.

**Comment by lhupe** [comment]
just a quick note: I have had a similar problem (World age issues with `ismutabletype`) when accidentally running Julia with the  `--compiled-modules=no` flag. Don't know whether that's related to the original issue though

**Comment by JonasIsensee** [comment]
I figured out the issue:

`ismutabletype` is used in `@generated` functions that are defined further up in the code than `ismutabletype`.

Depending on when the compiler decides to *generate* the functions this causes worldage problems.
I've solved this by moving the definition further up.
