### ISSUE TITLE
Expose file header verification

### ISSUE THREAD

**Issue by Octogonapus** [JuliaIO/JLD2.jl#326]
I have a need to detect JLD2 files without using their extension. I saw [this code](https://github.com/JuliaIO/JLD2.jl/blob/master/src/file_header.jl#L19) but it looks internal and also does more than I would like it to. I would like to expose a subset of this behavior in the API. How about:

1. Extracting the header check from `verify_file_header` into a new function that takes the same parameter `f`.
2. Introducing this function into the public API.

I am happy to PR this change if it would be welcome.

**Comment by JonasIsensee** [comment]
Hi @Octogonapus !
This is a good idea but it's actually not needed to modify any code for this.
`FileIO` already has good mechanisms for detecting file formats. (and it is a dependency of `JLD2`)

You can do
```
julia> using JLD2

julia> @save "testfile" a=rand(5)


julia> JLD2.FileIO.query("testfile")
FileIO.File{FileIO.DataFormat{:JLD2}, String}("/home/isensee/testfile")

julia> using FileIO

julia> FileIO.query("testfile")
File{DataFormat{:JLD2}, String}("/home/isensee/testfile")
```


which, if necessary, you could further dissect by doing
```
julia> f = FileIO.query("testfile")
File{DataFormat{:JLD2}, String}("/home/isensee/testfile")

julia> typeof(f).parameters[1].parameters[1]
:JLD2

```

**Comment by Octogonapus** [comment]
Thanks, I did not know about `FileIO.query`.
