### ISSUE TITLE
Error `DataType has no field ninitialized` when saving Tuple

### ISSUE THREAD

**Issue by jlapeyre** [JuliaIO/JLD2.jl#327]
```julia
julia> import JLD2

julia> JLD2.save("tst.jld2", "x", (1,2))
Error encountered while save FileIO.File{FileIO.DataFormat{:JLD2}, String}("tst.jld2").

Fatal error:
ERROR: type DataType has no field ninitialized
...
```

 [033835bb] JLD2 v0.4.9

Julia: Version 1.7.0-DEV.1290, 6e8754337a*

EDIT:
The bug does *not* occur in
Julia 1.7.0-DEV.961, 2435f96f92*

**Comment by BoundaryValueProblems** [comment]
Yes, I have exactly the same problem.

**Comment by JonasIsensee** [comment]
As I mentioned in #320 
Julia is changing internals too fast for me to keep up at the moment.

https://github.com/JuliaIO/JLD2.jl/issues/320#issuecomment-860171006

The way forward is to figure out what has changed in julia and change the code in JLD2 accordingly. 
(Using `@static if VERSION < v"1.7.0-A"` blocks to keep compatibility to earlier versions)

**Comment by JonasIsensee** [comment]
This appears to be the culprit
https://github.com/JuliaLang/julia/pull/41018

**Comment by PaulSoderlind** [comment]
another data point: same problem on Julia-1.7.0-beta2 when saving a Dict
```
using FileIO, JLD2
D = Dict("a"=>"Hazel")
save("test.jld2","D",D)
```
gives 
```
Error encountered while save File{DataFormat{:JLD2}, String}("test.jld2").                          
                                                  
Fatal error:                                      
ERROR: LoadError: type DataType has no field ninitialized      ...
```
