### ISSUE TITLE
JLD2 doesn't recognise types during Documenter builds

### ISSUE THREAD

**Issue by AayushSabharwal** [JuliaIO/JLD2.jl#328]
Hi! I'm trying to generate documentation, some of which uses JLD2. If I define a struct, and `@save` it, it works. However, when loading back in, JLD2 doesn't recognise the struct type even though it's in the same module. This only occurs during Documenter builds. Consider the following mockup:

<details>
  <summary>mockup.jl file</summary>
  
```julia
using Agents
using JLD2

struct FooAgent <: AbstractAgent
    id::Int
    pos::Tuple{Int,Int}
    foo::String
end

# This is some markdown stuff

agents = [FooAgent(i, (i, i), "$i") for i in 1:10]

# This is some more markdown stuff

@save "test.jld2" agents

# Now that something is saved

agents = nothing
@load "test.jld2" agents

# Did it load properly?

println(agents)
println(typeof(agents))
println(typeof(agents[1]))

# Hmmm
```
  
</details>

Using `Literate.markdown("mockup.jl")`

<details>
  <summary>mockup.md</summary>
  
````
 ```@meta
EditURL = "<unknown>/src/mockup.jl"
```   

```@example mockup
using Agents
using JLD2

struct FooAgent <: AbstractAgent
    id::Int
    pos::Tuple{Int,Int}
    foo::String
end
```

This is some markdown stuff

```@example mockup
agents = [FooAgent(i, (i, i), "$i") for i in 1:10]
```

This is some more markdown stuff

```@example mockup
@save "test.jld2" agents
```

Now that something is saved

```@example mockup
agents = nothing
@load "test.jld2" agents
```

Did it load properly?

```@example mockup
println(agents)
println(typeof(agents))
println(typeof(agents[1]))
```

Hmmm

---

*This page was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*
````
 
</details>

After building as a Documenter page:
![image](https://user-images.githubusercontent.com/23384717/122042330-a263d580-cdf7-11eb-860c-64806768aa43.png)

The type is reconstructed even though it was defined right there.

**Comment by JonasIsensee** [comment]
Hi @AayushSabharwal 

JLD2 usually throws a warning when it cannot reconstruct a struct. Can you please check the stderr (e.g. CI log ?)
for warnings?
Do you get the same behaviour, when you use `FileIO.load` ?

**Comment by AayushSabharwal** [comment]
There aren't any warnings in the CI log about this. The only time it complains is when I try to use the data, since it's not compatible with other functions and data structures.

as for `FileIO.load`, there isn't any change:
![image](https://user-images.githubusercontent.com/23384717/122051925-c24cc680-ce02-11eb-97d4-5554b8c6bcb9.png)

**Comment by JonasIsensee** [comment]
![image](https://user-images.githubusercontent.com/33990604/122065011-e5bb4580-cdf1-11eb-96fd-4a617918863b.png)


This is odd and is not a problem with JLD2. There is something funky going on with the modules the code is being evaluated into

**Comment by Libbum** [comment]
Hmm, indeed. Looks like that module is [coming from documenter](https://github.com/JuliaDocs/Documenter.jl/blob/c942201b745abbdf155c880e1231cb8240507b41/src/Expanders.jl#L535).

**Comment by JonasIsensee** [comment]
It should be possible to fool `JLD2` , though.
Defining
```
julia> module Foo
       struct Bar
       x
       end
       @eval Main Baz = $(@__MODULE__)
       end
Main.Foo

julia> Baz
Main.Foo

julia> Baz.Bar
Main.Foo.Bar
```

**Comment by AayushSabharwal** [comment]
This fixes the docs build. Thanks!
