### ISSUE TITLE
"load not defined" because of implicitly requiring FileIO

### ISSUE THREAD

**Issue by leohallier** [JuliaIO/JLD2.jl#333]
I shared code with someone that used the `load` function for loading JLD2 data, which I sent with the code. They did not have FileIO installed, so they got "UndefVarError: load not defined". I could have prevented this by writing `using FileIO` in my code but I did not see this coming, so maybe others will not either. 
Therefore I think this implicit requirement of FileIO is not good, as it can cause problems when code is shared. Maybe there can be a warning, when `load` is being used when FileIO is not installed.

**Comment by JonasIsensee** [comment]
Hi,
in the newest versions of JLD2 FileIO is an explicit dependency. 

Can you please check whether you are on the latest version?

**Comment by leohallier** [comment]
Oh, I have not thought about the impact of package versions. I have the newest version (and have not updated since the issues arose) but I do not know the version history of the recipient. However, if it is explicit now, then there is nothing that can be done about issues with older versions.
