### ISSUE TITLE
How to handle reconstructed types?

### ISSUE THREAD

**Issue by vandenman** [JuliaIO/JLD2.jl#334]
Hi! I ran a simulation study where I saved each intermediate result to disk (28000 files) and I encountered an issue where a `Tuple{Int64, Tuple, Int64, Int64, Float64, Int64}` is loaded as a reconstructed type.

Consider the example below that uses this [data](https://github.com/JuliaIO/JLD2.jl/files/6747215/jld2_issue.jld2.zip):
```julia
using JLD2
data = JLD2.load("jld2_issue.jld2"); # one of the saved simulation runs

reconstructed_data = data["sim"]

reconstructed_data[1] # error

function reconstructed_to_tuple(x)
	Tuple(
		if getfield(x, i) isa UInt
			Int(getfield(x, i))
		else
			getfield(x, i)
		end
		for i in 1:nfields(x)
	)
end

reconstructed_data_tuple = reconstructed_to_tuple(reconstructed_data)
reconstructed_data_tuple[1]
```
prints:
```julia
julia> using JLD2

julia> data = JLD2.load("old_files/jld2_issue.jld2");
┌ Warning: read type Tuple{Int64, Tuple, Int64, Int64, Float64, Int64} is not a leaf type in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/sFiXk/src/data/reconstructing_datatypes.jl:125

julia> reconstructed_data = data["sim"]
JLD2.ReconstructedTypes.var"##Tuple{Int64, Tuple, Int64, Int64, Float64, Int64}#333"(100, ("betabinom11",), 5, 20, 0.2, 4)

julia> reconstructed_data[1] # error
ERROR: MethodError: no method matching getindex(::JLD2.ReconstructedTypes.var"##Tuple{Int64, Tuple, Int64, Int64, Float64, Int64}#333", ::Int64)
Stacktrace:
 [1] top-level scope
   @ REPL[81]:1

julia> function reconstructed_to_tuple(x)
               Tuple(
                       if getfield(x, i) isa UInt
                               Int(getfield(x, i))
                       else
                               getfield(x, i)
                       end
                       for i in 1:nfields(x)
               )
       end
reconstructed_to_tuple (generic function with 1 method)

julia> reconstructed_data_tuple = reconstructed_to_tuple(reconstructed_data)
(100, ("betabinom11",), 5, 20, 0.2, 4)

julia> reconstructed_data_tuple[1]
100
```

Now I have two questions:
1. Is this warning (`┌ Warning: read type Tuple{Int64, Tuple, Int64, Int64, Float64, Int64} is not a leaf type in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/sFiXk/src/data/reconstructing_datatypes.jl:125)` something to worry about? It does seem to introduce a serious performance penalty.
2. Is there a better way than the function `reconstructed_to_tuple` to transform the reconstructed data back to its original type? I know for a fact that all the Ints are Int64, but sometimes the reconstructed type has UInt64 (hence the if statement).

I briefly tried to create a reproducible example where saving and reloading would create a reconstructed type, but I didn't succeed. If you think this would be useful I'd be happy to give it another try!

**Comment by JonasIsensee** [comment]
Hi @vandenman ,

this is indeed quite annoying and should probably be considered a bug.
The underlying issue is the following:
- Your tuple with `("betabinom11", )` contains an anonymous function or closure `#48#54`.
- JLD2 currently does not support anonymous functions ( see #316 )
- JLD2 fails in an odd way when encountering unknown functions inside tuples (and doesn't warn you about it)
- The warning that you are getting: just states that `Tuple{Int64, Tuple, Int64, Int64, Float64, Int64}` is not an allowed type signature (see the `Tuple` there ? ) That should be something like `Tuple{Int64, Tuple{String, typeof(#48#54)}, Int64, Int64, Float64, Int64}` but `#48#54` is not known in your session.

Hacky workaround for this particular file: Just define the function 
```
julia> using JLD2

julia> var"48#54"(x)=x^2
48#54 (generic function with 1 method)

julia> load("jld2_issue.jld2")
Dict{String, Any} with 9 entries:
  "included"     => Bool[1 0 … 0 0; 0 1 … 0 0; … ; 1 0 … 1 0; 0 1 … 0 1]
  "sim"          => (100, ("betabinom11", 48#54), 5, 20, 0.2, 4)
  "mean_θ_cs_eq" => [-0.179863; 0.223458; … ; -0.283581; 0.151553]
  "incl_probs"   => [1.0 0.0 … 0.0 0.0; 0.18085 1.0 … 0.0 0.0; … ; 0.5827 0.1252 … 1.0 0.0; 0.2575 0.60315 … 0.1653 1…
  "seed"         => 871
  "θ_cs_eq"      => [0.036445 -0.352896 … 6.66134e-17 6.66134e-17; 0.182308 0.235264 … 6.66134e-17 6.66134e-17; … ; -…
  "priorname"    => "betabinom11"
  "true_values"  => Dict{Symbol, Union{Float64, Vector{Float64}, Vector{Int64}}}(:μ=>0.0, :σ=>1.0, :θ=>[-0.28, 0.32, …
  "true_model"   => [2, 5, 4, 3, 3]

```

**Comment by vandenman** [comment]
Thanks a lot, @JonasIsensee! That workaround is very useful. My apologies, I did read that anonymous functions are not supported by I completely forgot I had actually saved these to disk. For my 28000 files, there are only six distinct anonymous functions. If I define those first then there is a huge speed boost in loading the files.
