### ISSUE TITLE
DataType has now field mutable

### ISSUE THREAD

**Issue by Cvikli** [JuliaIO/JLD2.jl#337]
Hey,

I am facing with the error of:
`ERROR: LoadError: type DataType has no field mutable`

I tried to use v0.4.11, v0.4.10 and v0.4.9 to solve the problem but nothing helped. Does anyone know why is this happening?

**Comment by JonasIsensee** [comment]
Hi,

julia internals have changed a bit recently in development versions. From your message, I assume that you are using a julia 1.7 development version but without more information, I can't help you. 

What exact julia +package versions are you using and whaz did you do to produce the error?

**Comment by dpo** [comment]
Same error with Julia nightly: https://github.com/JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl/pull/43/checks?check_run_id=3147069185#step:6:86

All I do is `jldopen(..., "r")`: https://github.com/JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl/blob/main/src/SuiteSparseMatrixCollection.jl#L16

**Comment by dpo** [comment]
I thought the issue might be that `jlopen` was called inside `__init__`, but apparently, that's not it.

**Comment by JonasIsensee** [comment]
> Same error with Julia nightly: https://github.com/JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl/pull/43/checks?check_run_id=3147069185#step:6:86
> 
> All I do is `jldopen(..., "r")`: https://github.com/JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl/blob/main/src/SuiteSparseMatrixCollection.jl#L16

Hm, your link to CI does not point anywhere. Maybe logs were deleted in the meantime?

**Comment by dpo** [comment]
https://github.com/JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl/runs/3147069185?check_suite_focus=true#step:6:86

**Comment by JonasIsensee** [comment]
I can't tell you why, but at the very top of the logs there is a warning:
```
[ Info: The General registry already exists locally
     Testing SuiteSparseMatrixCollection
┌ Warning: Could not use exact versions of packages in manifest, re-resolving
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1489
      Status `/tmp/jl_hT7t1p/Project.toml`
  [a93c6f00] DataFrames v0.21.8
  [033835bb] JLD2 v0.4.3
```

where julia then proceeds to install `JLD2 v0.4.3`. Only the latest version `v0.4.11` works with julia nightly.

**Comment by dpo** [comment]
In the meantime, I found that upgrading DataFrames made the error go away.
