### ISSUE TITLE
where is jldsave ?

### ISSUE THREAD

**Issue by avigliotti** [JuliaIO/JLD2.jl#339]
Hi,

just installed the package but I can't find the jldsave function, I also searched the files in the ```src``` folder with 

```grep jldsave *.jl```

but didn't find no occurrence, was it removed from the package?

many thanks in advance,
Andrea

**Comment by JonasIsensee** [comment]
https://github.com/JuliaIO/JLD2.jl/blob/ee85fa7774b032e230c1a69529cfe85e5af23d5a/src/loadsave.jl#L239

How about this?

**Comment by avigliotti** [comment]
I don't have that line in my ```loadsave.jl```, actually my version of the file stops at line 215, 

I added ```JLD2``` through the package manager and I have ```[033835bb] JLD2 v0.4.3``` but now github is at ```v0.4.11```, should I have added it with different means?

if I try 

```(@v1.5) pkg>  add "https://github.com/JuliaIO/JLD2.jl" ```

I get this error

```ERROR: Unsatisfiable requirements detected for package Reexport [189a3867]:
 Reexport [189a3867] log:
 ├─possible versions are: [0.2.0, 1.0.0, 1.1.0] or uninstalled
 ├─restricted to versions 1 by JLD2 [033835bb], leaving only versions [1.0.0, 1.1.0]
 │ └─JLD2 [033835bb] log:
 │   ├─possible versions are: 0.4.11 or uninstalled
 │   └─JLD2 [033835bb] is fixed to version 0.4.11
 └─restricted by compatibility requirements with JuliaFEM [f80590ac] to versions: 0.2.0 — no versions left
   └─JuliaFEM [f80590ac] log:
     ├─possible versions are: 0.5.0-0.5.1 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.5.0-0.5.1
````

**Comment by JonasIsensee** [comment]
JLD2 has a dependency on the package `Reexport` with a version requirement of `> 1` so there are two valid releases for that package. `1.0.0` and `1.1.0`.
However, you also have `JuliaFEM` installed that (indirectly) requires `Reexport` with version `0.2.0`.

The quickest way to install a newer version of JLD2 will be to uninstall `JuliaFEM`.
However, if you are actively using that package, you will need to find out 
why JuliaFEM requires `Reexport` v0.2.0. (This may also be an indirect dependency)

**Comment by avigliotti** [comment]
great, thank you very much for your explanations!
