### ISSUE TITLE
" too many parameters for type" error

### ISSUE THREAD

**Issue by vijujames** [JuliaIO/JLD2.jl#341]
Compiling latest (07/29) throws the following error 
@JonasIsensee 

[ Info: ===== Start precompile execution =====
ERROR: LoadError: too many parameters for type
Stacktrace:
 [1] _precompile_() at /home/ubuntu/.julia/packages/JLD2/m5olh/src/precompile.jl:45
 [2] top-level scope at /home/ubuntu/.julia/packages/JLD2/m5olh/src/JLD2.jl:525
 [3] include(::Function, ::Module, ::String) at ./Base.jl:380
 [4] include(::Module, ::String) at ./Base.jl:368
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:347 [inlined]
 [7] eval(::Expr) at ./client.jl:467
 [8] top-level scope at ./none:3
in expression starting at /home/ubuntu/.julia/packages/JLD2/m5olh/src/JLD2.jl:523

**Comment by JonasIsensee** [comment]
Hi @vijujames,

Can you please give me a bit of additional information?
What operatingsystem  are you using and what julia version?

**Comment by vijujames** [comment]
Hi @JonasIsensee,

Ubuntu 18.04.5 LTS
julia version 1.5.4

Our Julia project has been working/compiling until yesterday. Today it stopped compiling after updating the dependencies. After looking at the commits - found some changes related to JLD2 version check. Not sure if it is related, but the error is coming from JLD2

**Comment by JonasIsensee** [comment]
Hi @vijujames ,

thanks for pointing this out so quickly. The precompile file was added only today.
julia v1.5 is not officially supported anymore and JLD2 does not test whether it works there.
I opened a PR to include the precompile block only for `> v1.6.0`

**Comment by vijujames** [comment]
@JonasIsensee thank you for fixing it quickly
