### ISSUE TITLE
Issue with reading Union element type array, element type of array changes after accessing it

### ISSUE THREAD

**Issue by KristofferC** [JuliaIO/JLD2.jl#348]
Let's say we want to save a few arrays with 

```jl
using JLD2

function rand_gen!(x, p = 0.1)
    for i in 1:length(x)
        x[i] = rand() < p ? rand(Float32) : rand(Float64)
    end
    return x
end
 
test_io = jldopen("type_unions.jld2", "w");

var = Vector{Union{Float64, Float32}}(undef, 1000);
for t in 1:5
    rand_gen!(var, 0.2)
    test_io[string(t)] = copy(var);
end
close(test_io)
```

We then read the data back in and look at the element type of one of the arrays:

```jl
julia> f = jldopen("type_unions.jld2", "r");

julia> eltype(f["1"])
Union{Float32, Float64}

julia> eltype(f["1"])
JLD2.InlineUnionEl{Float32, Float64}

julia> eltype(f["1"])
JLD2.InlineUnionEl{Float32, Float64}
```

It is surprising that the element type would change like that after accessing the array the first time. I would guess this is a bug?

**Comment by JonasIsensee** [comment]
Fascinating. That is a definitely a 🐛.

What must be happening:
JLD2 retains a `WeakRef` to mutable objects when loading to speed up subsequent accesses. It appears that it is caching the data prior to converting.

**Comment by JonasIsensee** [comment]
fixed it. Thanks for reporting!

**Comment by KristofferC** [comment]
Thanks for such a quick fix!
