### ISSUE TITLE
Drag & Drop loading of files

### ISSUE THREAD

**Issue by VoSiLk** [JuliaIO/JLD2.jl#360]
Hi,

sometimes I miss the drag & drop feature from MATLAB for mat-files. There you just drag a mat-file to the command window and it will be automatically loaded. Something similar for jld2-files to REPL in VSCode or Atom woulde be nice. I'm not aware of something like this. I know, that it isn't so important, but sometimes I just would like to have a quick look into the jld2-file without copying the path and everything.

Best regards

**Comment by JonasIsensee** [comment]
Hi @VoSiLk ,
if I understand correctly, then this is purely an IDE thing.
There is nothing JLD2 can do to support this.
