### ISSUE TITLE
Segfault when trying to load this file

### ISSUE THREAD

**Issue by chelseas** [JuliaIO/JLD2.jl#363]
[run_99801_worst_cells.zip](https://github.com/JuliaIO/JLD2.jl/files/7722412/run_99801_worst_cells.zip)

Title says it all. 

I tried to save it with jldsave and the kwarg syntax of jldsave("filename.jld2", a=5, b = 6) type thing.

**Comment by JonasIsensee** [comment]
The file itself is fine. It loads without errors in a clean julia session (without `SymEngine` being loaded).
I don't know what's causing the segfault for you, but I'm hopeful that we can get this fixed with a dedicated `custom serialization` as discussed in #362
