### ISSUE TITLE
Issue saving large amounts of data

### ISSUE THREAD

**Issue by BoZenKhaa** [JuliaIO/JLD2.jl#367]
When trying to save large amount of data, I get
```julia
Fatal error:
ERROR: LoadError: InexactError: trunc(UInt16, 80540)

Stacktrace:                                                                                                 
  [1] throw_inexacterror(f::Symbol, #unused#::Type{UInt16}, val::Int64)                                     
    @ Core ./boot.jl:612                                                                                    
  [2] checked_trunc_uint                                                                                    
    @ ./boot.jl:642 [inlined]                                                                               
  [3] toUInt16                                                                                                           
    @ ./boot.jl:715 [inlined]
  [4] UInt16
    @ ./boot.jl:765 [inlined]
  [5] convert
    @ ./number.jl:7 [inlined]
  [6] JLD2.HeaderMessage(msg_type::UInt8, size::Int64, flags::Int64)                                        
    @ JLD2 ~/.julia/packages/JLD2/DcnTD/src/object_headers.jl:63
  [7] commit(f::JLD2.JLDFile{JLD2.MmapIO}, dt::JLD2.CompoundDatatype, attrs::Tuple{JLD2.WrittenAttribute{JLD2
.WriteDataspace{0, Tuple{}}, JLD2.CommittedDatatype, DataType}, JLD2.WrittenAttribute{JLD2.WriteDataspace{1, 
Tuple{}}, JLD2.BasicDatatype, Vector{JLD2.RelOffset}}})
#.....
```

It seems the failure is caused by `Header.size` being limited to `UInt16`. Is this a hard limitation?

**Comment by JonasIsensee** [comment]
Hi @BoZenKhaa, 

can you give me more information on what you were trying to store?
Maybe we can find a workaround.

From the stacktrace it looks like you were trying to store a very complex struct. 
Also #343

**Comment by BoZenKhaa** [comment]
Hello @JonasIsensee, thank you for looking into this, you are right, after investigating further, the data being stored is below 100MB, but it has a bit of structure to it. 

I am struggling to produce workable MWE, since I got the data by saving larger and larger instances of same stuff, and I had the first failure after couple of iterations. 

The data is generally a dictionary that looks like this, saved through `DrWatson.jl` as `Dict("data"=>dict_below)`:
```
Dict{Symbol, Any} with 2 entries:
  :pp        => PMDPProblem{6, 3, 10}(PMDPs.Product[[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [0, 1, 1], [1, 1, 1]], [3, 3, 3], 24, StaggeredB…
  :traces    => SimHistory{NamedTuple{(:s, :a, :sp, :r, :info, :t, :action_info), Tuple{PMDPs.State{3}, Float64, PMDPs.State{3}, Float64, NamedT…
```
where the `:pp` is a subtype of MDP from `POMDPs.jl` and contains subtypes from `Distributions.jl` anf `StaticArrays.jl`. 
The `:traces` is a vector of thousands of `POMDPs.jl` [`SimHistories`](https://github.com/JuliaPOMDP/POMDPSimulators.jl/blob/master/src/history.jl) generated by the `PMDPProblem`. Each `SimHistory` is a vector-like structures of MDP states. 

The larger instances that fail to save are generated by increasing the parameters of the `PMDPProblem`, which increases the dimensions of all the structures contained within.

The the structure that seems to be causing the issue is the `SimHistory` type inside the `:traces` vector (saving an array with just one of these for parameter 20 fails):
```
SimHistory{NamedTuple{(:s, :a, :sp, :r, :info, :t, :action_info), Tuple{PMDPs.State{20}, Float64, PMDPs.State{20}, Float64, NamedTuple{(:b,), Tuple{Float64}}, Int64, Nothing}}, Float64}
```
where `State` is 
```
struct State{n_res}
    c::SVector{n_res,Int64}  
    t::Int64               
    iₚ::Int64        
end
```

I work around this now by not using larger instances. I started from `BSON.jl` that I saw being used in `DrWatson` docs, but I had too many issues with it, so I switched to `JLD2`.  Going forward, I think I will try using `Serialization.serialize`

**Comment by JonasIsensee** [comment]
ok, so this `SVector{n_res,Int}` is probably the culprit.
SVectors are statically sized and are therefore inlined for serialization.
This is great for performance when the SVectors are short and terrible when they become too long.

Building on the example from #343 :

**Comment by JonasIsensee** [comment]
might work now

**Comment by BoZenKhaa** [comment]
Thank you @JonasIsensee for looking into this! JLD2 is so far the best  way of saving and loading Julia structures I have come across. In my project, I have decided to drop dependence on StaticArrays, it was bringing me more hassle than benefits.
