### ISSUE TITLE
`jldsave` description in README.md should be improved a bit

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaIO/JLD2.jl#371]
Hello. I think it would be better to emphasize the importance of `;` in the description of `jldsave` function in README.md.
If you simply use `,` instead of `;` when you start listing the variables to be saved, you got errors like:
```
x = randn(100);
jldsave("./tmp.jld2", x)
ERROR: ArgumentError: Unsupported Compressor
Supported Compressors are 
        CodecBzip2.Bzip2Compressor
        CodecLz4.LZ4FrameCompressor
        CodecZlib.ZlibCompressor
Stacktrace:
 [1] verify_compressor(compressor::Vector{Float64})
   @ JLD2 ~/.julia/packages/JLD2/L21uR/src/compression.jl:27
 [2] jldopen(fname::String, wr::Bool, create::Bool, truncate::Bool, iotype::Type{JLD2.MmapIO}; fallback::Type{IOStream}, compress::Vector{Float64}, mmaparrays::Bool)
   @ JLD2 ~/.julia/packages/JLD2/L21uR/src/JLD2.jl:250
 [3] jldopen(fname::String, mode::String; iotype::Type, kwargs::Base.Pairs{Symbol, Vector{Float64}, Tuple{Symbol}, NamedTuple{(:compress,), Tuple{Vector{Float64}}}})
   @ JLD2 ~/.julia/packages/JLD2/L21uR/src/JLD2.jl:342
 [4] jldopen(::JLD2.var"#56#57"{Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:compress,), Tuple{Bool}}}}, ::String, ::Vararg{String}; kws::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:compress, :iotype), Tuple{Vector{Float64}, DataType}}})
   @ JLD2 ~/.julia/packages/JLD2/L21uR/src/loadsave.jl:2
 [5] #jldsave#55
   @ ~/.julia/packages/JLD2/L21uR/src/loadsave.jl:243 [inlined]
 [6] top-level scope
   @ REPL[26]:1
```

Of course, it should be `jldsave("./tmp.jld2"; x)` instead of `jldsave("./tmp.jld2", x)`. But people tend to use `,`, especially, `,` is fine in the other functions of JLD2 in README.md, e.g., `load` and `save` functions.
So, perhaps, just add the following phrase in README.md would be sufficient and helpful for the users:
### A new interface: jldsave

`jldsave` makes use of julia's keyword argument syntax to store files,
thus leveraging the parser and not having to rely on macros. To use it, write

```julia
x = 1
y = 2
z = 42

# The simplest case:
jldsave("example.jld2"; x, y, z)
# it is equivalent to 
jldsave("example.jld2"; x=x, y=y, z=z)

# You can assign new names selectively
jldsave("example.jld2"; x, a=y, z)

# and if you want to confuse your future self and everyone else, do
jldsave("example.jld2"; z=x, x=y, y=z)
```

**In the above examples, `;` after the filename is important.** Compression and non-default IO types may be set via positional arguments.

Should I file a pull request?

Thanks!

**Comment by JonasIsensee** [comment]
Hi @BoundaryValueProblems ,
strictly speaking, the kwarg name recycling is a standard julia feature that only works after a `;` anyway.
However, that still sounds like a useful hint.
You're welcome to open a PR.
