### ISSUE TITLE
reading individual variables from a JLD2 files

### ISSUE THREAD

**Issue by avigliotti** [JuliaIO/JLD2.jl#378]
Hi,

is there a way to read specific variables fro a JLD2 files that contains many variables some of which are quite large, which means that reading the entire file can take long?

the file has been saved through FileIO as
```
FileIO.save(sFileName, Dict("x"=>x, "y"=>y, "z"=>z))
```
ideally, I would like to be able to do something like
```
x = FileIO.load(sFileName, "x")
```
similar to what you can do in `matlab`

**Comment by lhupe** [comment]
yes, that should work exactly as you suggested
```
julia> FileIO.save("foo.jld2", Dict("x"=>[1,2,3,4], "y"=>[5,6,7,8], "z"=>[9,10,11,12]))
julia> FileIO.load("foo.jld2", "x")
4-element Vector{Int64}:
 1
 2
 3
 4
```

**Comment by avigliotti** [comment]
that's great thanks!
I din't see it in the documentation and I assumed was not there
