### ISSUE TITLE
is the package not mainteined ?

### ISSUE THREAD

**Issue by avigliotti** [JuliaIO/JLD2.jl#379]
here [JLD2](https://juliahub.com/ui/Packages/JLD2/O1EyT/0.1.14) it says "WARNING: This package is not actively maintained and has several known bugs that are unlikely to be resolved in the near future", is that actually the case?

**Comment by lhupe** [comment]
the package was abandoned for a while, but has recently found a new maintainer in @JonasIsensee.
The JuliaHub entry you have linked is for an old version (v0.1.14, the package is currently on v0.4.20), so it still contains the warning in the README file.

**Comment by avigliotti** [comment]
great, thanks for the clarification.
