### ISSUE TITLE
Thoughts on addrequire?

### ISSUE THREAD

**Issue by timholy** [JuliaIO/JLD2.jl#39]
JLD supports [`addrequire`](https://github.com/JuliaIO/JLD.jl#types-and-their-definitions) to allow folks to ensure that necessary packages are loaded before objects from a JLD file. If you'd support this, I will eventually get around to submitting a PR.

**Comment by JonasIsensee** [comment]
This could actually be really neat!

I just took a look at the implementation in `JLD`.
I think it could be improved for JLD2:
- Use a `_requires` subgroup that contains entries for every requirement. That avoids having to delete a list over and over again  AND it would be readable using tools like `h5dump`.
- Attach version number of loaded package. This allows for future extension to warn users if there are major version number changes.

`f["_requires/DataFrames"] = versionofloadedpackage(DataFrames)`

**Comment by lbenet** [comment]
Any progress on this?

**Comment by JonasIsensee** [comment]
Hi @lbenet ,
there is #377 which implements something like this. The PR has been sitting around unused for a while since I wasn't super convinced, it was optimal but it does work.
You are welcome to test and give feedback.

**Comment by JonasIsensee** [comment]
One of the main potential applications of this feature would be to load *missing* packages.
This doesn't feel like it would be good practice anymore.
The alternative would be to throw an error but this already happens when trying to load.
So I'm closing this for now.
