### ISSUE TITLE
Warning: type does not exist in workspace; reconstructing

### ISSUE THREAD

**Issue by Amuri44** [JuliaIO/JLD2.jl#390]
I was using the below code to create .jld2 file containing an instance Sim of structure Simulation
```julia
include("./SimulationStructure.jl");
function appFunction()
Sim = Simulation();
io = open("$(@__DIR__)/generatedElements.jld2", "w")
close(io)
save("$(@__DIR__)/generatedElements.jld2", "Sim", Sim, "Simulation", Simulation)
end
appFunction();
```
in which SimulationStructure.jl:
```julia
using base
export Simulation 
Base.@kwdef mutable struct Simulation 
    dt::Float64 = 1e-6
    tmax::Float64 = 32*1e-3
end
```
Then, I was reading the created .jld2 by the below code called readFile.jl. and It was working without any warning, in which typeof Sim is Simulation
```julia
include("./SimulationStructure.jl");
Sim, Simulation = load("$(@__DIR__)/generatedElements.jld2", "Sim", "Simulation");
julia> typeof(Sim)
Simulation
```
Now, I have built executable for appFunction() as below and it works fine to generate the .jld2 file.
```julia
module readApp

Base.@ccallable function julia_main()::Cint
    try
        appFunction()
    catch
        Base.invokelatest(Base.display_error, Base.catch_stack())
        return 1
    end
    return 0
end

Base.@kwdef mutable struct Simulation 
  dt::Float64 = 1e-6
  tmax::Float64 = 32*1e-3
end

function appFunction()
Sim = Simulation();
save("$(@__DIR__)/generatedElements.jld2", "Sim", Sim, "Simulation", Simulation)
end
end
```
However, calling readFile.jl to read the generated .jld2 gives this warning and typeof Sim is Simulation
```julia
┌ Warning: type readApp.Simulation does not exist in workspace; reconstructing
└ @ JLD2 C:\Users\amroa\.julia\packages\JLD2\k9Gt0\src\data\reconstructing_datatypes.jl:461
julia> typeof(Sim)
JLD2.ReconstructedTypes.var"##readApp.Simulation#292"
julia> Simulation
JLD2.UnknownType{String}("testtest.Simulation", #undef)
```
How can I get ride of the warning and fix the typeof(Sim) to be of Simula JLD2 to be of Simulation?tion?

**Comment by JonasIsensee** [comment]
Dear @Amuri44 ,
let me first note that are completely unnecessary. You generate an empty file only to overwrite it directly afterwards.
```
io = open("$(@__DIR__)/generatedElements.jld2", "w")
close(io)
```

Concerning your error: Take a close look at the warning: `type readApp.Simulation does not exist in workspace`
JLD2 is looking for a struct called `Simulation` defined inside a module `readApp`. This is exactly how you generated it.
However, in the session where you try to read the file, you define `Main.Simulation` (by having a top-level struct definition).

You can either make sure to define `Simulation` same way in both cases, or load the struct as:

```
load(filename; typemap=Dict("readApp.Simulation" => Simulation))
```
for an explanation of what `typemap` does, have a look at the documentation website.

**Comment by Amuri44** [comment]
Dear @JonasIsensee Thank you very much for you explanation. I got it that the definition should be the same int both cases. However:
I have tried to work on the second casem but still `Sim` is not type of `Simulation`, please correct me:
```julia
include("./SimulationStructure.jl");
load("$(@__DIR__)/generatedElements.jld2"; typemap=Dict("readApp.Simulation" => Simulation))
Sim = load("$(@__DIR__)/generatedElements.jld2", "Sim")
julia> Sim
JLD2.ReconstructedTypes.var"##readApp.Simulation#292"(1.0e-6, 0.032)
```

**Comment by JonasIsensee** [comment]
You're nearly there. Do

```
julia> include("./SimulationStructure.jl")
julia> Sim = load("$(@__DIR__)/generatedElements.jld2"; typemap=Dict("readApp.Simulation" => Simulation))
julia> Sim
```

**Comment by Amuri44** [comment]
Thank you very much.
