### ISSUE TITLE
JLD2 saves PyObjects as NULL

### ISSUE THREAD

**Issue by morripau** [JuliaIO/JLD2.jl#411]
Here's a simple example. When my_scaler is loaded it's loaded as PyObject NULL. 

	using JLD2, ScikitLearn
	@sk_import preprocessing : StandardScaler
	
	X = zeros(5,2)

	for i = 1:5
		for j= 1:2
			X[i, j] = 2*i+j
		end
	end
	
	my_scaler = StandardScaler().fit(X)
	@save "my_scaler.jld2" my_scaler
	@load "my_scaler.jld2" my_scaler

	my_scaler

**Comment by JonasIsensee** [comment]
Hi @morripau ,

on the julia side, a `PyObject` is really just a pointer. 
Therefore the default is to just not store anything. (the pointer would be invalid upon loading)


However, it should be possible to implement something like https://github.com/JuliaPy/PyCallJLD.jl
for JLD2. Then, one would use pickle to serialize the pyobject and place the bytes into the JLD2 file.
