### ISSUE TITLE
List groups?

### ISSUE THREAD

**Issue by jlchan** [JuliaIO/JLD2.jl#419]
Is there a way to list the root-level groups in a loaded JLD2 file?

**Comment by JonasIsensee** [comment]
Hi @jlchan ,

can you please make your question a bit more specific?
A JLD2 file only has one single "root" group, namely "/".

**Comment by jlchan** [comment]
Apologies - yes, let me try. Suppose I have a file with structure
```julia
julia> file
JLDFile /Users/jessechan/Desktop/ES_CNS_splitting_paper/code/test.jld2 (read/write)
 ├─🔢 group_3
 ├─📂 group_1
 │  ├─🔢 subgroup_1
 │  └─🔢 subgroup_2
 └─📂 group_2
    ├─🔢 subgroup_1
    └─🔢 subgroup_2
```
is there a command which will list `group_1`, `group_2`, `group_3`? 

Thanks!

**Comment by JonasIsensee** [comment]
Is this what you are looking for?
̀```
julia> using JLD2

julia> save("test.jld2", "a/c", 1, "b",2)

julia> f = jldopen("test.jld2")
JLDFile /home/isensee/test.jld2 (read-only)
 ├─🔢 b
 └─📂 a
    └─🔢 c

julia> keys(f)
2-element Vector{String}:
 "b"
 "a"
```

**Comment by jlchan** [comment]
Yes, thank you!

**Comment by jlchan** [comment]
Thank you! That's great.
