### ISSUE TITLE
Determine required modules before loading

### ISSUE THREAD

**Issue by tecosaur** [JuliaIO/JLD2.jl#421]
It would be nice if there was a way to ask a `.jld2` file or contained data object what modules are needed to reconstruct it. I'm integrating JLD2 with something that already provides "load this module if possible" functionality, so it would be nice to use that to try to avoid `Warning: saved type DataFrame is missing field metadata in workspace type; reconstructing` -type issues.

**Comment by JonasIsensee** [comment]
hi @tecosaur,

have a look at #377.
I made a draft implementation for this at some point in the past.
