### ISSUE TITLE
Generated `@info`s for `chunk dims` when loading

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaIO/JLD2.jl#422]
Loading files, I'm getting many of these printed out:

```
chunk dims
tuple(chunk_dimensions...) :[0x0000000022f09200, 0x0000000000000800, ...]
dimensionality: 0x02
dimensionality_size: 0x08
chunk_indexing_type: 0x01
```

It seems to be generated by JLD2. Is this necessary?

**Comment by BioTurboNick** [comment]
Ah, it seems to be new as of 4.24 a few days ago?

https://github.com/JuliaIO/JLD2.jl/blob/b5c09ef8fcf36597d62b0d6dbbfd4cefb8fa5c12/src/object_headers.jl#L442

**Comment by PaulSoderlind** [comment]
possible to suppress this?

**Comment by BioTurboNick** [comment]
Sure, though it doesn't mean much to me as the user, so should it be emitted at all by default?

**Comment by JonasIsensee** [comment]
oh, this is my fault.
`v0.4.24` includes a large amount of new features and I must have missed a debug statement there.

**Comment by BioTurboNick** [comment]
No worries, thanks!

**Comment by JonasIsensee** [comment]
I didn't find any other leftover debug statements, so I just registered `v0.4.25` with that one line removed
