### ISSUE TITLE
recommended testing protocol

### ISSUE THREAD

**Issue by tpapp** [JuliaIO/JLD2.jl#43]
The readme cautions that the package

> has received little testing in the wild

I would like to help by testing on data I work with, and I am wondering what the recommended testing protocol is. My first-pass approach would be to write, read, and compare, but what's the recommended comparison operator that I should use? `iseq` from the unit tests?

**Comment by JonasIsensee** [comment]
I'd say this counts as outdated.

While the tests can sure use some work, there has been plenty of testing in the wild.

The things to test are whether saving and loading does not throw and
whether loaded results equal what was writtenj
