### ISSUE TITLE
Remove large_fractal_heap.h5 (60Mb) file from package? 

### ISSUE THREAD

**Issue by marius311** [JuliaIO/JLD2.jl#443]
Can the large 60MB large_fractal_heap.h5 file be removed frorm this repo, or its size reduced somehow? Eg between all my environments I have 4 different versions of JLD2 installed so 240MB from this file alone, which is a not-insignificant fraction of the 40GB home quota I have on a cluster I use alot.

**Comment by Datseris** [comment]
@JonasIsensee yeap that is easy. Have a look of how we did it for Agents.jl for including a map of goettingen as a test data for Open Street Map. 

https://github.com/JuliaDynamics/Agents.jl/blob/main/src/spaces/openstreetmap.jl#L12

https://github.com/JuliaDynamics/Agents.jl/blob/main/src/spaces/openstreetmap.jl#L161-L170

https://github.com/JuliaDynamics/Agents.jl/blob/main/Artifacts.toml

**Comment by JonasIsensee** [comment]
> 

hmm, your example does not seem to work?
The artifacts.toml refers to `master` not main. But even if I change it to `main`, I can't access it or understand where this file would be located. -> It can't be in the repo, right?
