### ISSUE TITLE
No compression with `jldsave`

### ISSUE THREAD

**Issue by cafaxo** [JuliaIO/JLD2.jl#444]
With
```julia
jldsave("example1.jld2", compress=ZlibCompressor(); x=zeros(10_000))
```
I do not get any compression.
The following works fine:
```julia
jldopen("example2.jld2", "w"; compress = ZlibCompressor()) do f
    f["large_array"] = zeros(10_000)
end
```

**Comment by JonasIsensee** [comment]
Hm, it could be that the docstring is misleading here...
Try
`jldsave("example1.jld2", ZlibCompressor(); x=zeros(10_000))`


(without giving a name for the positional argument)

**Comment by cafaxo** [comment]
Yes, the docstring says
```julia
  jldsave(filename, compress=false; kwargs...)
```
It works without the `compress=`.
