### ISSUE TITLE
expost API for testing type consistency

### ISSUE THREAD

**Issue by tpapp** [JuliaIO/JLD2.jl#46]
If a user writes values of a type
```julia
struct Foo
    a::Int64
end
```
and then later redefines the type as
```julia
struct Foo
    a::Int64
    b::Int64
end
```
and reads from a `jld2` file, `JLD2` (and also, of course, `JLD`) can catch the inconsistency between the two definitions. It would be great have the API for this exposed, eg as `write_type_fingerprint(jldfile, "Foo", Foo)` and similarly as a read method.

**Comment by JonasIsensee** [comment]
I'm sorry, I don't quite understand what you are suggesting.

**Comment by tpapp** [comment]
A way to detect this situation before reading the data (and throwing an error).

**Comment by JonasIsensee** [comment]
This is now mostly possible through the string representations of datatypes using explicit datasets added in #568.
