### ISSUE TITLE
LoadError: type DataType has no field size

### ISSUE THREAD

**Issue by YANG-Hanbin** [JuliaIO/JLD2.jl#472]
Hi all, 

I'm using Julia 1.9, and want to use JLD2. However, there are errors:

julia> using JLD2
[ Info: Precompiling JLD2 [033835bb-8acc-5ee8-8aae-3f567f8a3819]
ERROR: LoadError: type DataType has no field size

I saw there is a similar issue and suggested that update DataFrames. I have tried this method but no help. Do you know what's going on?

Best,
Hanbin

**Comment by JonasIsensee** [comment]
Hi @YANG-Hanbin,

you most likely ended up with an ancient version of JLD2 because of some version conflict.
Please try to update your environment and see what is holding it back.

**Comment by YANG-Hanbin** [comment]
Thanks for your reply.

I have already upgraded JLD2 but the errors is staying there. I guess, this should be a problem with DataFrames?

Best,
Hanbin

**Comment by JonasIsensee** [comment]
No, that is very unlikely due to DataFrames.
Can you please post the package versions in your environment? (output of `Pkg.status()`)

**Comment by YANG-Hanbin** [comment]
Thank you for your patience!

julia> Pkg.status()
Status `~/.julia/environments/v1.9/Project.toml`
⌅ [46ada45e] Agents v4.5.7
  [7820620d] AgentsPlots v0.4.2
  [c52e3926] Atom v0.12.38
⌅ [336ed68f] CSV v0.8.5
⌃ [13f3f980] CairoMakie v0.6.3
  [9961bab8] Cbc v1.1.1
  [878138dc] CellularAutomata v0.0.2
  [e2554f3b] Clp v1.0.3
  [35d6a980] ColorSchemes v3.21.0
  [861a8166] Combinatorics v1.0.2
⌃ [a93c6f00] DataFrames v1.3.6
  [743a1d0a] DataTables v0.1.0
⌃ [31c24e10] Distributions v0.25.45
⌃ [634d3b9d] DrWatson v2.5.0
  [5789e2e9] FileIO v1.16.1
⌃ [587475ba] Flux v0.13.8
  [f6369f11] ForwardDiff v0.10.35
  [da1fdf0e] FreqTables v0.4.5
  [38e38edf] GLM v1.8.3
  [60bf3e95] GLPK v1.1.2
⌃ [5752ebe1] GMT v0.44.8
⌃ [28b8d3ca] GR v0.72.5
  [b16dfd50] GRIB v0.3.0
  [ddc7317b] GeoDatasets v0.1.7
  [0ef565a4] Geodesy v1.1.0
⌃ [3700c31b] GeophysicalModelGenerator v0.4.12
  [a2cc645c] GraphPlot v0.5.2
  [bd48cda9] GraphRecipes v0.5.12
  [86223c79] Graphs v1.8.0
  [2e9cd046] Gurobi v1.0.1
⌃ [f67ccb44] HDF5 v0.16.14
⌃ [7073ff75] IJulia v1.24.0
⌅ [82e4d734] ImageIO v0.5.9
⌃ [916415d5] Images v0.24.1
  [6deec6e2] IndexedTables v1.0.0
⌃ [ec714cd0] InteractiveDynamics v0.18.1
⌃ [b6b21f68] Ipopt v1.2.1
⌃ [033835bb] JLD2 v0.4.3
  [682c06a0] JSON v0.21.4
⌃ [4076af6c] JuMP v1.11.1
  [e5e0dc1b] Juno v0.8.4
⌃ [2b0e0bc5] LanguageServer v3.2.0
⌃ [23fbe1c1] Latexify v0.16.0
⌃ [b4f0291d] LazySets v2.7.6
  [093fc24a] LightGraphs v1.3.5
⌃ [9ecf9c4f] MeshViz v0.5.4
⌅ [eacbb407] Meshes v0.25.15
⌃ [37188c8d] MvNormalCDF v0.2.5
  [bac558e1] OrderedCollections v1.6.0
  [90014a1f] PDMats v0.11.17
⌃ [8314cec4] PGFPlotsX v1.5.1
  [07a8691f] PGLib v0.1.0
  [2dcacdae] ParallelDataTransfer v0.5.0
  [fad6cfc8] ParallelUtilities v0.8.6
⌃ [58dd65bb] Plotly v0.3.0
⌅ [a03496cd] PlotlyBase v0.5.4
⌅ [f0f68f2c] PlotlyJS v0.14.1
⌃ [91a5bcdd] Plots v1.38.12
  [c36e90e8] PowerModels v0.19.9
  [7425d11c] PowerModelsAnalytics v0.4.1
  [229d1e32] PowerPlots v0.4.7
  [27ebfcd6] Primes v0.5.3
  [d330b81b] PyPlot v2.11.1
  [1a8c2f83] Query v1.0.0
  [ce6b1742] RDatasets v0.7.7
⌅ [189a3867] Reexport v0.2.0
⌃ [f4570300] SDDP v0.4.6
⌅ [efcf1570] Setfield v0.7.1
⌅ [2913bbd2] StatsBase v0.33.21
  [f3b207a7] StatsPlots v0.15.5
  [a759f4b9] TimerOutputs v0.5.23
⌃ [b8865327] UnicodePlots v3.5.3
⌃ [1986cc42] Unitful v1.14.0
  [42071c24] UnitfulRecipes v1.6.1
  [770da0de] UpdateJulia v0.4.2
⌅ [112f6efa] VegaLite v2.6.0
  [d6d074c3] VideoIO v1.0.6
  [8ba89e20] Distributed
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [1a1011a3] SharedArrays
  [2f01184e] SparseArrays
  [8dfed614] Test
Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated`

Best,
Hanbin

**Comment by JonasIsensee** [comment]
Great!

Your JLD2 version is indeed ancient (because some compatibility problem prevents the update).

Can you please try the hint at the bottom of the message? (] status --outdated) 
It should tell you what packages could be problematic.
Try to uninstall those and update.
Then (if you really need then, add them back in)

**Comment by YANG-Hanbin** [comment]
Ohh, thank you!

But I'm confused about the output
⌃ [033835bb] JLD2 v0.4.3 (<v0.4.32).

This means that I can directly update it without compatibility problem. But I have tried but it still stay in version v0.4.3 istead of v0.4.32.

Should I just uninstall all of packages with ⌅? 

Best,
Hanbin

**Comment by YANG-Hanbin** [comment]
OH, I just understood the underlying logic behind this statement. Thanks!

Best,
Hanbin

**Comment by JonasIsensee** [comment]
Did you manage to fix it?

**Comment by YANG-Hanbin** [comment]
Yep, I created a new Julia environment and reloaded the needed packages.

Thank you!
