### ISSUE TITLE
Reconstructed types regression in v0.4.33

### ISSUE THREAD

**Issue by Octogonapus** [JuliaIO/JLD2.jl#479]
Maybe I should not call this a regression because we might be using internals, but here is the problem I'm facing:

In v0.4.33, PR #476 changed how reconstructed types work. Previously, JLD2 used to load something like `typeof(jld2_data) = JLD2.ReconstructedTypes.var"##Cap#292"` and `fieldnames(typeof(jld2_data)) = (<a tuple of the fieldnames of the type which was being reconstructed>)` (the actual code is private, sorry). Now in v0.4.33, I get `typeof(jld2_data) = Reconstruct@Cap` and `fieldnames(typeof(jld2_data)) = (:fields,)`. I'm not sure how to get the fieldnames anymore. Can you please advise?

I have to do all of this because the reconstructed type must fit into the type tree we have, otherwise dispatch breaks because the reconstructed type isn't a subtype of the right thing. E.g. we have:
```julia
abstract type Foo end
struct Bar end # imagine some fields

# imagine we save a Bar to a file, then add new fields to Bar, and load the Bar from the file
# we get a warning like "saved type Bar is missing field ... in workspace type, reconstructing"
# the reconstructed Bar is not a subtype of Foo, so this dispatch breaks:
function baz(any_foo::Foo)
end

# which means I must convert the JLD2 type into my type:
function Base.convert(::Type{T}, jld2_data) where {T<:Foo}
    U = fix_conversion_type_for_jld2(T, typeof(jld2_data))
    kwargs = Dict()
    for f in fieldnames(typeof(jld2_data))
        kwargs[f] = getfield(jld2_data, f)
    end
    return U(; kwargs...)
end

function fix_conversion_type_for_jld2(to, from)
    # i can't think of a better way to do this check than converting `from` into a string.
    # `string(from)` will look something like `JLD2.ReconstructedTypes.var"##MyModule.Bar#312"`
    return if to == Foo && contains(string(from), "MyModule.Bar")
        Bar
    else
        to
    end
end

**Comment by JonasIsensee** [comment]
Hi @Octogonapus ,

Would `propertynames` be acceptable for you to use? 

Question: are we allowed to redefine "fieldnames" for structs? If yes, you could easily add those definitions if JLD2. (The diff of the latest release should be straightforward to understand) 

The advantage of the new reconstruction is that it does not have to rely on eval and instead wraps the fields into a named tuple.

**Comment by Octogonapus** [comment]
Here is the output from that:
```julia
propertynames(jld2_data) = ()
propertynames(typeof(jld2_data)) = (:name, :super, :parameters, :types, :instance, :layout, :hash, :flags)
propertynames(jld2_data, true) = ()
propertynames(typeof(jld2_data), true) = (:name, :super, :parameters, :types, :instance, :layout, :hash, :flags)
JLD2.isreconstructed(jld2_data) = true
```

Did you expect to see the struct fields in the output from `propertynames`? In general, this function would be fine for me to use if it returned the property names of the saved struct.

> Question: are we allowed to redefine "fieldnames" for structs?

`fieldnames` is just a function so I guess you could?

Also in the process of debugging this, I found another related issue preventing `JLD2.load` from working. I've pushed the MWE here https://github.com/Octogonapus/jld2_reproducer. You can clone it and run `docker build --progress=plain .` to reproduce. The error I get is here https://pastebin.com/6n6chfMV

**Comment by JonasIsensee** [comment]
Oh, of course. fieldnames takes a datatype and gives you the field names it's instances have. propertynames takes an instance and gives you the property (field) names.

I'm away from a computer for a while but will test your mwe when i get the opportunity.

**Comment by JonasIsensee** [comment]
> Also in the process of debugging this, I found another related issue preventing JLD2.load from working. I've pushed the MWE here https://github.com/Octogonapus/jld2_reproducer. You can clone it and run docker build --progress=plain . to reproduce. The error I get is here https://pastebin.com/6n6chfMV

I reproduced your issue and tried to fix it.
Your example is fixable but it highlights a more fundamental problem: non-concrete type struct fields

```
abstract type MyAbstractType end

struct Container
    x::MyAbstractType
end
```

On a type level it is unknowable whether an instance of `Container` can be loaded or not because the subtype of `MyAbstractType` can be different each time.

**Comment by Octogonapus** [comment]
I guess in general, that is true. However, within our ecosystem, `Container` can always be loaded because we change the code in a such a way as to maintain this compatibility. I wouldn't want perfect to be the enemy of better here.

**Comment by JonasIsensee** [comment]
> Your example is fixable but it highlights a more fundamental problem: non-concrete type struct fields

I must partially retract my statement.... this is not really fixable. Very frustrating

**Comment by JonasIsensee** [comment]
If you are willing to do some "work", you can define:
```
# the first of the two will eventually land in JLD2 itself..
JLD2.rconvert(::Type{Array{T,N}}, x::Array{T2,N}) where {T, T2, N} = [JLD2.rconvert(T, y) for y in x]  
JLD2.rconvert(::Type{Baz}, t::JLD2.AbstractReconstructedType) = Baz(t.z1, 0)

# or directly
Base.convert(::Type{Baz}, t::JLD2.AbstractReconstructedType) = Baz(t.z1, 0)
```
