### ISSUE TITLE
 jldopen(filename, "w";) will fail in win7

### ISSUE THREAD

**Issue by HongBinYu-hub** [JuliaIO/JLD2.jl#508]
Hello,

I'm having trouble using JLD2.

In the win7 operating system, jldopen(filename, "w") defaults to iotype = MmapIO, which will cause an error. But jldopen(filename, "w"; iotype = IOStream) can be written normally. And due to this error, win7 will not be able to precompile the JLD2 library.

```
data = Dict("key" => "value")
filename = "demo.jld2"

jldopen(filename, "w") do f
    for (k, v) in pairs(data)
        f[string(k)] = v
    end
end
```

![jldopen报错](https://github.com/JuliaIO/JLD2.jl/assets/65697599/1b27098a-3ada-4767-95f1-559098507ed3)

**Comment by JonasIsensee** [comment]
This should be fixed now, no?

**Comment by HongBinYu-hub** [comment]
> This should be fixed now, no?

thanks a lot, On win7 system, this problem has been solved.
