### ISSUE TITLE
JLD2 is failed to precompile on the latest nightly

### ISSUE THREAD

**Issue by bvdmitri** [JuliaIO/JLD2.jl#550]
See for example [here](https://github.com/ReactiveBayes/GraphPPL.jl/actions/runs/7930894994/job/21654038566)
 The version is `[033835bb] JLD2 v0.4.45`.
 The error thrown is 
 ```julia
 caused by: MethodError: no method matching resize!(::Memory{UInt8}, ::Int64)
The function `resize!` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  resize!(::BitVector, ::Integer)
   @ Base bitarray.jl:814
  resize!(::Vector, ::Integer)
   @ Base array.jl:1433
  resize!(::JLD2.MmapIO, ::Ptr{Nothing})
   @ JLD2 ~/.julia/packages/JLD2/z3MOM/src/mmapio.jl:140
 ```
 I'm not sure, this might be a Julia bug, but decided to open it here first to be sure.

**Comment by JonasIsensee** [comment]
This also showed up in JLD2s tests a few days ago. I fixed it now in #551
