### ISSUE TITLE
How to print or show every group name of a JLD2 file

### ISSUE THREAD

**Issue by crazyfireji** [JuliaIO/JLD2.jl#553]
I open a JLD2 file and want to read it, but I forgot the name of the group, How to show all of the group[ name of the file 
![image](https://github.com/JuliaIO/JLD2.jl/assets/112403698/e6d87881-68cc-47d0-8449-70253b8325b2)

**Comment by JonasIsensee** [comment]
Try
```
julia> f = jldopen("test.jld2")
JLDFile /test.jld2 (read-only)
 └─🔢 foo

julia> keys(f)
1-element Vector{String}:
 "foo"
```

**Comment by crazyfireji** [comment]
> Try
> 
> ```
> julia> f = jldopen("test.jld2")
> JLDFile /test.jld2 (read-only)
>  └─🔢 foo
> 
> julia> keys(f)
> 1-element Vector{String}:
>  "foo"
> ```

Thank you very much!!!
