### ISSUE TITLE
Issue saving & loading larger nested dictionaries from v0.4.53 onwards

### ISSUE THREAD

**Issue by matthew-liu-1** [JuliaIO/JLD2.jl#603]
Currently working on a use case that involves saving large nested dictionaries and have recently upgraded JLD2 to **v0.5.3** from **v0.4.52**
After upgrading, dictionaries of an arbitrarily large size can no longer be saved & loaded properly.

This issue appears from JLD2 v0.4.53 onwards.

Analysis:
1. A large dictionary (see line 58 below) can be saved in JLD2 **v0.4.52** and loaded in JLD2 **v0.4.53**
2. A large dictionary (see line 58 below) **cannot be saved** and loaded in JLD2 **v0.4.53**

Reproducible code example:
https://github.com/matthew-liu-1/JLD2.jl/blob/large_obj_issue/test/jld2_io_error/error_script.jl

System information:
Julia version: 1.10.4
RAM: 32 gb
CPU:  13th Gen Intel(R) Core(TM) i7-13700H

**Comment by JonasIsensee** [comment]
Thank you for this report. That made it easy to reproduce and possible to track down the problem.

`v0.5.4` should fix this and be out later today.

**Comment by matthew-liu-1** [comment]
Thank you @JonasIsensee for the quick turnaround!
