### ISSUE TITLE
Option to allow reconstructing mutable struct 

### ISSUE THREAD

**Issue by ngphuoc** [JuliaIO/JLD2.jl#70]
I would like to save a mutable struct then restore it later mutable. I'd like the restore to be anonymous. How could I make it mutable without explicitly redefining the struct in the target code?

```julia
mutable struct Point
  x
  y
end
p = Point(1,2)
using FileIO
save("point.jld2", Dict("p"=>p))

# open a new julia
using FileIO
p = load("point.jld2", "p")
  # WARNING: type Point does not exist in workspace; reconstructing
p.x
p.y = 3
  # ERROR: type ##Point#661 is immutable

```

**Comment by simonster** [comment]
If you define the type before loading the file, it will be mutable.

**Comment by JonasIsensee** [comment]
Yeah, I don't see a point in this either.
Reconstructing types that are not defined in the workspace is meant to just be a last option.
Usage should not depend on this.
