### ISSUE TITLE
Option to read slices of stored arrays

### ISSUE THREAD

**Issue by vilim** [JuliaIO/JLD2.jl#71]
Is it possible to read parts of arrays stored as JLD2 files (a specific slice), like in the HDF5.jl example?
```
using HDF5
h5read("/tmp/test2.h5", "mygroup2/A", (2:3:15, 3:5))
```

**Comment by JonasIsensee** [comment]
As of version v0.4.53 Dataset objects support getindex and setindex! which should behave as the syntax suggests.
