### ISSUE TITLE
Interaction with PyCallJLD

### ISSUE THREAD

**Issue by stakaz** [JuliaIO/JLD2.jl#83]
Hello, does this package allow to save Python objects as well? For JLD the package PyCallJLD was needed. When so, do JLD2 and PyCallJLD work nicely together? Thanks.

**Comment by JonasIsensee** [comment]
It is very likely that one would need something like `PyCallJLD` for JLD2 as well.
However `JLD2` is not directly compatible to `PyCallJLD`.
On the other hand the source code of `PyCallJLD` is just 36 lines, so it shouldn't be too hard.
