### ISSUE TITLE
error on 0.7-beta2, Win64

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaIO/JLD2.jl#84]
```
using JLD2, FileIO
x = "Dogs are nicer than cats"
@save "bark.jld2" x
``` 
crashes with an error message 
```ERROR: MethodError: Cannot `convert` an object of type Base.Libc.WindowsRawSocket to an object of type Int64```

/Paul S

**Comment by JonasIsensee** [comment]
This was taken care of by #92
