### ISSUE TITLE
Save anonymous functions (as part of a struct)

### ISSUE THREAD

**Issue by stakaz** [JuliaIO/JLD2.jl#86]
Hello, I have the following (basic) setup and I want to know whether it is possible to do such stuff or not:

```julia
using JLD2
A = ntuple(d->(x->x), 2)
@save "test.jld2" A
```
In a new session
```julia
using JLD2
@load "test.jld2"
```

This does **not** load the functions but recreates a tuple of symbols which can't be evaluated.

Is it intended behavior or a functionality not implemented yet.

**Comment by JonasIsensee** [comment]
closing this because it is reported in e.g. #175
